//package Part3;
//
//import org.junit.jupiter.api.Test;
//
//import java.util.ArrayList;
//import java.util.Arrays;
//import java.util.List;
//
//import static org.junit.jupiter.api.Assertions.assertEquals;
//class NumericalLetterGradeTest {
//    @Test
//    public void testNumericalLetterGrade() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(4.0);
//        grades.add(3);
//        grades.add(1.7);
//        grades.add(2);
//        grades.add(3.5);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("A+");
//        expected.add("B");
//        expected.add("C-");
//        expected.add("C");
//        expected.add("A-");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade2() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(1.2);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("D+");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade3() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(0.5);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("D-");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade4() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(0.0);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("E");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade5() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(1);
//        grades.add(0.3);
//        grades.add(1.5);
//        grades.add(2.8);
//        grades.add(3.3);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("D");
//        expected.add("D-");
//        expected.add("C-");
//        expected.add("B");
//        expected.add("B+");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade6() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(0);
//        grades.add(0.7);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("E");
//        expected.add("D-");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade7() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(4.0);
//        grades.add(3.7);
//        grades.add(3.3);
//        grades.add(3.0);
//        grades.add(2.7);
//        grades.add(2.3);
//        grades.add(2.0);
//        grades.add(1.7);
//        grades.add(1.3);
//        grades.add(1.0);
//        grades.add(0.7);
//        grades.add(0.0);
//        List<String> result = NumericalLetterGrade.numericalLetterGrade(grades);
//        List<String> expected = new ArrayList<String>();
//        expected.add("A+");
//        expected.add("A");
//        expected.add("A-");
//        expected.add("B+");
//        expected.add("B");
//        expected.add("B-");
//        expected.add("C+");
//        expected.add("C");
//        expected.add("C-");
//        expected.add("D+");
//        expected.add("D");
//        expected.add("E");
//        assertEquals(expected, result);
//    }
//
//    @Test
//    public void testNumericalLetterGrade8() {
//        List<Number> grades = new ArrayList<Number>();
//        grades.add(4.0);
//        grades.add(3.7);
//        grades.add(3.3);
//        grades.add(3.0);
//        grades.add(2.7);
//        grades.add(2.3);
//        grades.add(2.0);
//        grades.add(1.7);
//        grades.add(1.3);
//        grades.add(1.0);
//        grades.add(0.7);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
//        grades.add(0.0);
