// BomberClient_1Test.java
package client;

import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Observable;
import java.util.Vector;
import javax.swing.ImageIcon;
import messages.Message;
import messages.global.InfoRequestMsg;
import messages.global.JoinSessionMsg;
import messages.global.MapInfo;
import messages.global.SessionDetailsMsg;
import messages.round.ClientQuitRunningSessionMsg;
import org.apache.log4j.Logger;
import client.gui.StartFrame;
import client.network.ClientMsgReceiver;
import client.network.ClientMsgSender;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link BomberClient}.
* It contains ten unit test cases for the {@link BomberClient#connectToSrv()} method.
*/
class BomberClient_1Test {

    private static final Logger logger = Logger.getLogger(BomberClient_1Test.class);
    private static final String serverName = "localhost";
    private static final int serverPort = 1234;
    private static Socket server;
    private static ClientMsgSender msgSender;
    private static ClientMsgReceiver msgReceiver;
    private static BomberClient client;
    private static StartFrame startFrame;

    @Test
    void connectToSrv_1() {
        client = new BomberClient();
        startFrame = new StartFrame(client);
        startFrame.setVisible(true);
        startFrame.setServerName(serverName);
        startFrame.setServerPort(serverPort);
        startFrame.setStartButtonEnabled(true);
        startFrame.setStartButtonIcon(new ImageIcon("src/main/resources/images/start.png"));
        startFrame.setStartButtonText("Start");
        startFrame.setStartButtonToolTipText("Start");
        startFrame.setStartButtonVisible(true);
        startFrame.setStopButtonEnabled(false);
        startFrame.setStopButtonIcon(new ImageIcon("src/main/resources/images/stop.png"));
        startFrame.setStopButtonText("Stop");
        startFrame.setStopButtonToolTipText("Stop");
        startFrame.setStopButtonVisible(false);
        startFrame.setConnectButtonEnabled(true);
        startFrame.setConnectButtonIcon(new ImageIcon("src/main/resources/images/connect.png"));
        startFrame.setConnectButtonText("Connect");
        startFrame.setConnectButtonToolTipText("Connect");
        startFrame.setConnectButtonVisible(true);
        startFrame.setDisconnectButtonEnabled(false);
        startFrame.setDisconnectButtonIcon(new ImageIcon("src/main/resources/images/disconnect.png"));
        startFrame.setDisconnectButtonText("Disconnect");
        startFrame.setDisconnectButtonToolTipText("Disconnect");
        startFrame.setDisconnectButtonVisible(false);
        startFrame.setServerStatus("Disconnected");
        startFrame.setServerStatusIcon(new ImageIcon("src/main/resources/images/disconnected.png"));
        startFrame.setServerStatusToolTipText("Disconnected");
        startFrame.setServerStatusVisible(true);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusColor(java.awt.Color.RED);
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusTextForeground(java.awt.Color.WHITE);
        startFrame.setServerStatusTextBackground(java.awt.Color.RED);
        startFrame.setServerStatusText("Disconnected");
        startFrame.setServerStatusTextVisible(true);
        startFrame.setServerStatusTextFont(new java.awt.Font("Dialog", 0, 12));
        startFrame.setServerStatusText