// ModelManager_2Test.java
package com.eteks.sweethome3d.j3d;

import java.awt.EventQueue;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Area;
import java.awt.geom.GeneralPath;
import java.awt.geom.PathIterator;
import java.awt.geom.Rectangle2D;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.media.j3d.Appearance;
import javax.media.j3d.BoundingBox;
import javax.media.j3d.Bounds;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Geometry;
import javax.media.j3d.GeometryArray;
import javax.media.j3d.GeometryStripArray;
import javax.media.j3d.Group;
import javax.media.j3d.IndexedGeometryArray;
import javax.media.j3d.IndexedGeometryStripArray;
import javax.media.j3d.IndexedQuadArray;
import javax.media.j3d.IndexedTriangleArray;
import javax.media.j3d.IndexedTriangleFanArray;
import javax.media.j3d.IndexedTriangleStripArray;
import javax.media.j3d.Light;
import javax.media.j3d.Link;
import javax.media.j3d.Material;
import javax.media.j3d.Node;
import javax.media.j3d.QuadArray;
import javax.media.j3d.RenderingAttributes;
import javax.media.j3d.Shape3D;
import javax.media.j3d.SharedGroup;
import javax.media.j3d.Texture;
import javax.media.j3d.TextureAttributes;
import javax.media.j3d.Transform3D;
import javax.media.j3d.TransformGroup;
import javax.media.j3d.TransparencyAttributes;
import javax.media.j3d.TriangleArray;
import javax.media.j3d.TriangleFanArray;
import javax.media.j3d.TriangleStripArray;
import javax.vecmath.Color3f;
import javax.vecmath.Matrix3f;
import javax.vecmath.Point3d;
import javax.vecmath.Point3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;
import org.apache.batik.parser.AWTPathProducer;
import org.apache.batik.parser.ParseException;
import org.apache.batik.parser.PathParser;
import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.HomePieceOfFurniture;
import com.eteks.sweethome3d.tools.TemporaryURLContent;
import com.eteks.sweethome3d.tools.URLContent;
import com.microcrowd.loader.java3d.max3ds.Loader3DS;
import com.sun.j3d.loaders.IncorrectFormatException;
import com.sun.j3d.loaders.Loader;
import com.sun.j3d.loaders.ParsingErrorException;
import com.sun.j3d.loaders.Scene;
import com.sun.j3d.loaders.lw3d.Lw3dLoader;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModelManager}.
* It contains ten unit test cases for the {@link ModelManager#getNormalizedTransform(Node, float[][], float)} method.
*/
class ModelManager_2Test {

    @Test
    void testGetNormalizedTransform() {
        // Create a model with a single triangle
        float[][] modelRotation = new float[][] {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}};
        float width = 1;
        float[][] modelRotation2 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width2 = 1;
        float[][] modelRotation3 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width3 = 1;
        float[][] modelRotation4 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width4 = 1;
        float[][] modelRotation5 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width5 = 1;
        float[][] modelRotation6 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width6 = 1;
        float[][] modelRotation7 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width7 = 1;
        float[][] modelRotation8 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width8 = 1;
        float[][] modelRotation9 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width9 = 1;
        float[][] modelRotation10 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width10 = 1;
        float[][] modelRotation11 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width11 = 1;
        float[][] modelRotation12 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width12 = 1;
        float[][] modelRotation13 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width13 = 1;
        float[][] modelRotation14 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width14 = 1;
        float[][] modelRotation15 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width15 = 1;
        float[][] modelRotation16 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width16 = 1;
        float[][] modelRotation17 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width17 = 1;
        float[][] modelRotation18 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width18 = 1;
        float[][] modelRotation19 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width19 = 1;
        float[][] modelRotation20 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width20 = 1;
        float[][] modelRotation21 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width21 = 1;
        float[][] modelRotation22 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width22 = 1;
        float[][] modelRotation23 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width23 = 1;
        float[][] modelRotation24 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width24 = 1;
        float[][] modelRotation25 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width25 = 1;
        float[][] modelRotation26 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width26 = 1;
        float[][] modelRotation27 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width27 = 1;
        float[][] modelRotation28 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width28 = 1;
        float[][] modelRotation29 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width29 = 1;
        float[][] modelRotation30 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width30 = 1;
        float[][] modelRotation31 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width31 = 1;
        float[][] modelRotation32 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width32 = 1;
        float[][] modelRotation33 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width33 = 1;
        float[][] modelRotation34 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width34 = 1;
        float[][] modelRotation35 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width35 = 1;
        float[][] modelRotation36 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width36 = 1;
        float[][] modelRotation37 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width37 = 1;
        float[][] modelRotation38 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width38 = 1;
        float[][] modelRotation39 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width39 = 1;
        float[][] modelRotation40 = new float[][] {{1, 0, 0}, {0, 0, 1}, {0, 1, 0}};
        float width40 = 1;
        float[][] modelRotation41 = new float[][] {{0, 0, 1}, {0, 1, 0}, {1, 0, 0}};
        float width41 = 1;
        float[][] modelRotation42 = new float[][] {{0, 1, 0}, {1, 0, 0}, {0, 0, 1}};
        float width42 = 1;
        float[][] modelRotation43 = new float[][] {{1, 0, 0}, {0, 0, 