// TextureChoiceComponentTest.java
package com.eteks.sweethome3d.swing;

import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.KeyboardFocusManager;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.lang.ref.WeakReference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.TransferHandler;
import javax.swing.border.EtchedBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import com.eteks.sweethome3d.model.CatalogTexture;
import com.eteks.sweethome3d.model.CollectionEvent;
import com.eteks.sweethome3d.model.CollectionListener;
import com.eteks.sweethome3d.model.HomeTexture;
import com.eteks.sweethome3d.model.TextureImage;
import com.eteks.sweethome3d.model.TexturesCatalog;
import com.eteks.sweethome3d.model.TexturesCategory;
import com.eteks.sweethome3d.model.UserPreferences;
import com.eteks.sweethome3d.tools.OperatingSystem;
import com.eteks.sweethome3d.viewcontroller.TextureChoiceController;
import com.eteks.sweethome3d.viewcontroller.TextureChoiceView;
import com.eteks.sweethome3d.viewcontroller.View;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link TextureChoiceComponent}.
* It contains ten unit test cases for the {@link TextureChoiceComponent#confirmDeleteSelectedCatalogTexture()} method.
*/
class TextureChoiceComponentTest {

    private static final String TEST_TEXTURE_NAME = "testTextureName";
    private static final String TEST_TEXTURE_DESCRIPTION = "testTextureDescription";
    private static final String TEST_TEXTURE_CATEGORY = "testTextureCategory";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION = "testTextureCategoryDescription";
    private static final String TEST_TEXTURE_CATEGORY_NAME = "testTextureCategoryName";
    private static final String TEST_TEXTURE_CATEGORY_NAME_2 = "testTextureCategoryName2";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_2 = "testTextureCategoryDescription2";
    private static final String TEST_TEXTURE_CATEGORY_NAME_3 = "testTextureCategoryName3";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_3 = "testTextureCategoryDescription3";
    private static final String TEST_TEXTURE_CATEGORY_NAME_4 = "testTextureCategoryName4";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_4 = "testTextureCategoryDescription4";
    private static final String TEST_TEXTURE_CATEGORY_NAME_5 = "testTextureCategoryName5";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_5 = "testTextureCategoryDescription5";
    private static final String TEST_TEXTURE_CATEGORY_NAME_6 = "testTextureCategoryName6";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_6 = "testTextureCategoryDescription6";
    private static final String TEST_TEXTURE_CATEGORY_NAME_7 = "testTextureCategoryName7";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_7 = "testTextureCategoryDescription7";
    private static final String TEST_TEXTURE_CATEGORY_NAME_8 = "testTextureCategoryName8";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_8 = "testTextureCategoryDescription8";
    private static final String TEST_TEXTURE_CATEGORY_NAME_9 = "testTextureCategoryName9";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_9 = "testTextureCategoryDescription9";
    private static final String TEST_TEXTURE_CATEGORY_NAME_10 = "testTextureCategoryName10";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_10 = "testTextureCategoryDescription10";
    private static final String TEST_TEXTURE_CATEGORY_NAME_11 = "testTextureCategoryName11";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_11 = "testTextureCategoryDescription11";
    private static final String TEST_TEXTURE_CATEGORY_NAME_12 = "testTextureCategoryName12";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_12 = "testTextureCategoryDescription12";
    private static final String TEST_TEXTURE_CATEGORY_NAME_13 = "testTextureCategoryName13";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_13 = "testTextureCategoryDescription13";
    private static final String TEST_TEXTURE_CATEGORY_NAME_14 = "testTextureCategoryName14";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_14 = "testTextureCategoryDescription14";
    private static final String TEST_TEXTURE_CATEGORY_NAME_15 = "testTextureCategoryName15";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_15 = "testTextureCategoryDescription15";
    private static final String TEST_TEXTURE_CATEGORY_NAME_16 = "testTextureCategoryName16";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_16 = "testTextureCategoryDescription16";
    private static final String TEST_TEXTURE_CATEGORY_NAME_17 = "testTextureCategoryName17";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_17 = "testTextureCategoryDescription17";
    private static final String TEST_TEXTURE_CATEGORY_NAME_18 = "testTextureCategoryName18";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_18 = "testTextureCategoryDescription18";
    private static final String TEST_TEXTURE_CATEGORY_NAME_19 = "testTextureCategoryName19";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_19 = "testTextureCategoryDescription19";
    private static final String TEST_TEXTURE_CATEGORY_NAME_20 = "testTextureCategoryName20";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_20 = "testTextureCategoryDescription20";
    private static final String TEST_TEXTURE_CATEGORY_NAME_21 = "testTextureCategoryName21";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_21 = "testTextureCategoryDescription21";
    private static final String TEST_TEXTURE_CATEGORY_NAME_22 = "testTextureCategoryName22";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_22 = "testTextureCategoryDescription22";
    private static final String TEST_TEXTURE_CATEGORY_NAME_23 = "testTextureCategoryName23";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_23 = "testTextureCategoryDescription23";
    private static final String TEST_TEXTURE_CATEGORY_NAME_24 = "testTextureCategoryName24";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_24 = "testTextureCategoryDescription24";
    private static final String TEST_TEXTURE_CATEGORY_NAME_25 = "testTextureCategoryName25";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_25 = "testTextureCategoryDescription25";
    private static final String TEST_TEXTURE_CATEGORY_NAME_26 = "testTextureCategoryName26";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_26 = "testTextureCategoryDescription26";
    private static final String TEST_TEXTURE_CATEGORY_NAME_27 = "testTextureCategoryName27";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_27 = "testTextureCategoryDescription27";
    private static final String TEST_TEXTURE_CATEGORY_NAME_28 = "testTextureCategoryName28";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_28 = "testTextureCategoryDescription28";
    private static final String TEST_TEXTURE_CATEGORY_NAME_29 = "testTextureCategoryName29";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_29 = "testTextureCategoryDescription29";
    private static final String TEST_TEXTURE_CATEGORY_NAME_30 = "testTextureCategoryName30";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_30 = "testTextureCategoryDescription30";
    private static final String TEST_TEXTURE_CATEGORY_NAME_31 = "testTextureCategoryName31";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_31 = "testTextureCategoryDescription31";
    private static final String TEST_TEXTURE_CATEGORY_NAME_32 = "testTextureCategoryName32";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_32 = "testTextureCategoryDescription32";
    private static final String TEST_TEXTURE_CATEGORY_NAME_33 = "testTextureCategoryName33";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_33 = "testTextureCategoryDescription33";
    private static final String TEST_TEXTURE_CATEGORY_NAME_34 = "testTextureCategoryName34";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_34 = "testTextureCategoryDescription34";
    private static final String TEST_TEXTURE_CATEGORY_NAME_35 = "testTextureCategoryName35";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_35 = "testTextureCategoryDescription35";
    private static final String TEST_TEXTURE_CATEGORY_NAME_36 = "testTextureCategoryName36";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_36 = "testTextureCategoryDescription36";
    private static final String TEST_TEXTURE_CATEGORY_NAME_37 = "testTextureCategoryName37";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_37 = "testTextureCategoryDescription37";
    private static final String TEST_TEXTURE_CATEGORY_NAME_38 = "testTextureCategoryName38";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_38 = "testTextureCategoryDescription38";
    private static final String TEST_TEXTURE_CATEGORY_NAME_39 = "testTextureCategoryName39";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_39 = "testTextureCategoryDescription39";
    private static final String TEST_TEXTURE_CATEGORY_NAME_40 = "testTextureCategoryName40";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_40 = "testTextureCategoryDescription40";
    private static final String TEST_TEXTURE_CATEGORY_NAME_41 = "testTextureCategoryName41";
    private static final String TEST_TEXTURE_CATEGORY_DESCRIPTION_41 = "testTextureCategoryDescription41";
    private static final String TEST_TEXTURE_CATEGORY_NAME_42 = "testTextureCategoryName42";
    private