// MessageFactory_6Test.java
package module;

import util.AbstractFactory;
import module.Message;
import java.util.ResourceBundle;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link MessageFactory}.
* It contains ten unit test cases for the {@link MessageFactory#createErrorMessage(String, Object[])} method.
*/
class MessageFactory_6Test {

	/**
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
	* Test case 1 for method createErrorMessage.
