// ModelManager_3Test.java
package com.eteks.sweethome3d.j3d;

import java.awt.EventQueue;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Area;
import java.awt.geom.GeneralPath;
import java.awt.geom.PathIterator;
import java.awt.geom.Rectangle2D;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.media.j3d.Appearance;
import javax.media.j3d.BoundingBox;
import javax.media.j3d.Bounds;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Geometry;
import javax.media.j3d.GeometryArray;
import javax.media.j3d.GeometryStripArray;
import javax.media.j3d.Group;
import javax.media.j3d.IndexedGeometryArray;
import javax.media.j3d.IndexedGeometryStripArray;
import javax.media.j3d.IndexedQuadArray;
import javax.media.j3d.IndexedTriangleArray;
import javax.media.j3d.IndexedTriangleFanArray;
import javax.media.j3d.IndexedTriangleStripArray;
import javax.media.j3d.Light;
import javax.media.j3d.Link;
import javax.media.j3d.Material;
import javax.media.j3d.Node;
import javax.media.j3d.QuadArray;
import javax.media.j3d.RenderingAttributes;
import javax.media.j3d.Shape3D;
import javax.media.j3d.SharedGroup;
import javax.media.j3d.Texture;
import javax.media.j3d.TextureAttributes;
import javax.media.j3d.Transform3D;
import javax.media.j3d.TransformGroup;
import javax.media.j3d.TransparencyAttributes;
import javax.media.j3d.TriangleArray;
import javax.media.j3d.TriangleFanArray;
import javax.media.j3d.TriangleStripArray;
import javax.vecmath.Color3f;
import javax.vecmath.Matrix3f;
import javax.vecmath.Point3d;
import javax.vecmath.Point3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;
import org.apache.batik.parser.AWTPathProducer;
import org.apache.batik.parser.ParseException;
import org.apache.batik.parser.PathParser;
import com.eteks.sweethome3d.model.Content;
import com.eteks.sweethome3d.model.HomePieceOfFurniture;
import com.eteks.sweethome3d.tools.TemporaryURLContent;
import com.eteks.sweethome3d.tools.URLContent;
import com.microcrowd.loader.java3d.max3ds.Loader3DS;
import com.sun.j3d.loaders.IncorrectFormatException;
import com.sun.j3d.loaders.Loader;
import com.sun.j3d.loaders.ParsingErrorException;
import com.sun.j3d.loaders.Scene;
import com.sun.j3d.loaders.lw3d.Lw3dLoader;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModelManager}.
* It contains ten unit test cases for the {@link ModelManager#loadModel(Content)} method.
*/
class ModelManager_3Test {

    /**
     * Test method for {@link ModelManager#loadModel(Content)}.
     */
    @Test
    void testLoadModel() throws IOException {
        // Test with a model with a single piece of furniture
        final HomePieceOfFurniture piece = new HomePieceOfFurniture();
        piece.setName("piece");
        piece.setTextureName("texture");
        piece.setCategoryName("category");
        piece.setFurnitureName("furniture");
        piece.setWallName("wall");
        piece.setCeilingName("ceiling");
        piece.setFloorName("floor");
        piece.setDrawersName("drawers");
        piece.setEndsName("ends");
        piece.setElevatorsName("elevators");
        piece.setSlidersName("sliders");
        piece.setWindowsName("windows");
        piece.setDoorsName("doors");
        piece.setRoomsName("rooms");
        piece.setTablesName("tables");
        piece.setChairsName("chairs");
        piece.setShelvesName("shelves");
        piece.setObjectsName("objects");
        piece.setToolsName("tools");
        piece.setHeight(10);
        piece.setWidth(10);
        piece.setDepth(10);
        piece.setLength(10);
        piece.setX(10);
        piece.setY(10);
        piece.setZ(10);
        piece.setPitch(10);
        piece.setRoll(10);
        piece.setYaw(10);
        piece.setWallHeight(10);
        piece.setCeilingHeight(10);
        piece.setFloorHeight(10);
        piece.setDrawersHeight(10);
        piece.setEndsHeight(10);
        piece.setElevatorsHeight(10);
        piece.setSlidersHeight(10);
        piece.setWindowsHeight(10);
        piece.setDoorsHeight(10);
        piece.setRoomsHeight(10);
        piece.setTablesHeight(10);
        piece.setChairsHeight(10);
        piece.setShelvesHeight(10);
        piece.setObjectsHeight(10);
        piece.setToolsHeight(10);
        piece.setFurnitureDepth(10);
        piece.setFurnitureHeight(10);
        piece.setFurnitureWidth(10);
        piece.setFurnitureLength(10);
        piece.setFurnitureX(10);
        piece.setFurnitureY(10);
        piece.setFurnitureZ(10);
        piece.setFurniturePitch(10);
        piece.setFurnitureRoll(10);
        piece.setFurnitureYaw(10);
        piece.setFurnitureWallHeight(10);
        piece.setFurnitureCeilingHeight(10);
        piece.setFurnitureFloorHeight(10);
        piece.setFurnitureDrawersHeight(10);
        piece.setFurnitureEndsHeight(10);
        piece.setFurnitureElevatorsHeight(10);
        piece.setFurnitureSlidersHeight(10);
        piece.setFurnitureWindowsHeight(10);
        piece.setFurnitureDoorsHeight(10);
        piece.setFurnitureRoomsHeight(10);
        piece.setFurnitureTablesHeight(10);
        piece.setFurnitureChairsHeight(10);
        piece.setFurnitureShelvesHeight(10);
        piece.setFurnitureObjectsHeight(10);
        piece.setFurnitureToolsHeight(10);
        piece.setFurnitureShape("shape");
        piece.setFurnitureColor(10);
        piece.setFurnitureCutOutShape("cutOutShape");
        piece.setFurnitureCutOutColor(10);
        piece.setFurnitureCutOutHeight(10);
        piece.setFurnitureCutOutWidth(10);
        piece.setFurnitureCutOutLength(10);
        piece.setFurnitureCutOutX(10);
        piece.setFurnitureCutOutY(10);
        piece.setFurnitureCutOutZ(10);
        piece.setFurnitureCutOutPitch(10);
        piece.setFurnitureCutOutRoll(10);
        piece.setFurnitureCutOutYaw(10);
        piece.setFurnitureCutOutWallHeight(10);
        piece.setFurnitureCutOutCeilingHeight(10);
        piece.setFurnitureCutOutFloorHeight(10);
        piece.setFurnitureCutOutDrawersHeight(10);
        piece.setFurnitureCutOutEndsHeight(10);
        piece.setFurnitureCutOutElevatorsHeight(10);
        piece.setFurnitureCutOutSlidersHeight(10);
        piece.setFurnitureCutOutWindowsHeight(10);
        piece.setFurnitureCutOutDoorsHeight(10);
        piece.setFurnitureCutOutRoomsHeight(10);
        piece.setFurnitureCutOutTablesHeight(10);
        piece.setFurnitureCutOutChairsHeight(10);
        piece.setFurnitureCutOutShelvesHeight(10);
        piece.setFurnitureCutOutObjectsHeight(10);
        piece.setFurnitureCutOutToolsHeight(10);
        piece.setFurnitureCutOutShape("cutOutShape");
        piece.setFurnitureCutOutColor(10);
        piece.setFurnitureCutOutHeight(10);
        piece.setFurnitureCutOutWidth(10);
        piece.setFurnitureCutOutLength(10);
        piece.setFurnitureCutOutX(10);
        piece.setFurnitureCutOutY(10);
        piece.setFurnitureCutOutZ(10);
        piece.setFurnitureCutOutPitch(10);
        piece.setFurnitureCutOutRoll(10);
        piece.setFurnitureCutOutYaw(10);
        piece.setFurnitureCutOutWallHeight(10);
        piece.setFurnitureCutOutCeilingHeight(10);
        piece.setFurnitureCutOutFloorHeight(10);
        piece.setFurnitureCutOutDrawersHeight(10);
        piece.setFurnitureCutOutEndsHeight(10);
        piece.setFurnitureCutOutElevatorsHeight(10);
        piece.setFurnitureCutOutSlidersHeight(10);
        piece.setFurnitureCutOutWindowsHeight(10);
        piece.setFurnitureCutOutDoorsHeight(10);
        piece.setFurnitureCutOutRoomsHeight(10);
        piece.setFurnitureCutOutTablesHeight(10);
        piece.setFurnitureCutOutChairsHeight(10);
        piece.setFurnitureCutOutShelvesHeight(10);
        piece.setFurnitureCutOutObjectsHeight(10);
        piece.setFurnitureCutOutToolsHeight(10);
        piece.setFurnitureCutOutShape("cutOutShape");
        piece.setFurnitureCutOutColor(10);
        piece.setFurnitureCutOutHeight(10);
        piece.setFurnitureCutOutWidth(10);
        piece.setFurnitureCutOutLength(10);
        piece.setFurnitureCutOutX(10);
        piece.setFurnitureCutOutY(10);
        piece.setFurnitureCutOutZ(10);
        piece.setFurnitureCutOutPitch(10);
        piece.setFurnitureCutOutRoll(10);
        piece.setFurnitureCutOutYaw(10);
        piece.setFurnitureCutOutWallHeight(10);
        piece.setFurnitureCutOutCeilingHeight(10);
        piece.setFurnitureCutOutFloorHeight(10);
        piece.setFurnitureCutOutDrawersHeight(10);
        piece.setFurnitureCutOutEndsHeight(10);
        piece.setFurnitureCutOutElevatorsHeight(10);
        piece.setFurnitureCutOutSlidersHeight(10);
        piece.setFurnitureCutOutWindowsHeight(10);
        piece.setFurnitureCutOutDoorsHeight(10);
        piece.setFurnitureCutOutRoomsHeight(10);
        piece.setFurnitureCutOutTablesHeight(10);
        piece.setFurnitureCutOutChairsHeight(10);
        piece.setFurnitureCutOutShelvesHeight(10);
        piece.setFurnitureCutOutObjectsHeight(10);
        piece.setFurnitureCutOutToolsHeight(10);
        piece.setFurnitureCutOutShape("cutOutShape");
        piece.setFurnitureCutOutColor(10);
        piece.setFurnitureCutOutHeight(10);
        piece.setFurnitureCutOutWidth(10);
        piece.setFurnitureCutOutLength(10);
        piece.setFurnitureCutOutX(10);
        piece.setF