// UserTest.java
package com.browsersoft.aacs;

import java.io.Serializable;
import java.security.MessageDigest;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import java.util.StringTokenizer;
import javax.naming.ldap.LdapContext;
import org.apache.xerces.impl.dv.util.Base64;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link User}.
* It contains ten unit test cases for the {@link User#checkDigest(String, String)} method.
*/
class UserTest {

    @Test
    void testCheckDigest() {
        User user = new User();
        user.setUserId("test");
        user.setIpAddr("127.0.0.1");
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.setAllowedips(new HashSet());
        user.setLdapContext(null);
        user.setCountry("DE");
        user.setOrg("Browsersoft");
        user.setUserName("test");
        user.setSurName("test");
        user.setEmail("<EMAIL>");
        user.setRoles(new HashSet());
        user.setGroups(new HashSet());
        user.setActivegroups(new HashSet());
        user.setPassvalidstart("20060101000000Z");
        user.setPassrenewal("20060101000000Z");
        user.setPasschange(false);
        user.