// ModernChatServer_6Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#sendBinaryMessage(BinaryMessage)} method.
*/
class ModernChatServer_6Test {

    /**
     * Test of sendBinaryMessage method, of class ModernChatServer.
     * @throws java.rmi.RemoteException
     */
    @Test
    void testSendBinaryMessage() throws RemoteException {
        System.out.println("sendBinaryMessage");
        BinaryMessage msg = new BinaryMessage();
        msg.setAction(IConstant.REQUEST);
        msg.setFromUserId(1);
        msg.setToUserId(2);
        msg.setRoomId(1);
        msg.setMsgId(1);
        msg.setMsgSize(100);
        msg.setMsgData(new byte[100]);
        msg.setMsgDate(Calendar.getInstance().getTime());
        msg.setMsgStatus(IConstant.ONLINE);
        msg.setMsgStatusDate(Calendar.getInstance().getTime());
        msg.setMsgStatusBy(1);
        msg.setMsgStatusByDate(Calendar.getInstance().getTime());
        msg.setMsgStatusByIp("127.0.0.1");
        msg.setMsgStatusByPort(1099);
        msg.setMsgStatusByOs("Windows");
        msg.setMsgStatusByBrowser("Chrome");
        msg.setMsgStatusByDevice("PC");
        msg.setMsgStatusByCountry("IR");
        msg.setMsgStatusByRegion("Tehran");
        msg.setMsgStatusByCity("Tehran");
        msg.setMsgStatusByZip("123456");
        msg.setMsgStatusByTimeZone("GMT+03:30");
        msg.setMsgStatusByLanguage("fa");
        msg.setMsgStatusByCountryName("Iran");
        msg.setMsgStatusByRegionName("Tehran");
        msg.setMsgStatusByCityName("Tehran");
        msg.setMsgStatusByZipName("123456");
        msg.setMsgStatusByTimeZoneName("GMT+03:30");
        msg.setMsgStatusByLanguageName("Persian");
        msg.setMsgStatusByCountryFlag("IR");
        msg.setMsgStatusByRegionFlag("IR");
        msg.setMsgStatusByCityFlag("IR");
        msg.setMsgStatusByZipFlag("IR");
        msg.setMsgStatusByTimeZoneFlag("IR");
        msg.setMsgStatusByLanguageFlag("IR");
        msg.setMsgStatusByCountryFlagUrl("IR");
        msg.setMsgStatusByRegionFlagUrl("IR");
        msg.setMsgStatusByCityFlagUrl("IR");
        msg.setMsgStatusByZipFlagUrl("IR");
        msg.setMsgStatusByTimeZoneFlagUrl("IR");
        msg.setMsgStatusByLanguageFlagUrl("IR");
        msg.setMsgStatusByCountryFlagEmoji("IR");
        msg.setMsgStatusByRegionFlagEmoji("IR");
        msg.setMsgStatusByCityFlagEmoji("IR");
        msg.setMsgStatusByZipFlagEmoji("IR");
        msg.setMsgStatusByTimeZoneFlagEmoji("IR");
        msg.setMsgStatusByLanguageFlagEmoji("IR");
        msg.setMsgStatusByCountryFlagEmojiUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicode("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicode("IR");
        msg.setMsgStatusByCityFlagEmojiUnicode("IR");
        msg.setMsgStatusByZipFlagEmojiUnicode("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicode("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicode("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShort("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCss("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCss("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCssUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCssCss("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCssCssUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCssCssCss("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByRegionFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByCityFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByZipFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByTimeZoneFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByLanguageFlagEmojiUnicodeShortCssCssCssCssUrl("IR");
        msg.setMsgStatusByCountryFlagEmojiUnicodeShortCssCssCssCssCss("IR");
        msg.setMsgStatusByRegionFlagEmoji