// ModernChatServer_9Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#signInAsAdmin(String, String)} method.
*/
class ModernChatServer_9Test {

    private static final String ADMIN_EMAIL = "<EMAIL>";
    private static final String ADMIN_PASSWORD = "<PASSWORD>";
    private static final String ADMIN_PASSWORD_ENC = "<PASSWORD>";
    private static final String ADMIN_NAME = "Admin";
    private static final String ADMIN_SURNAME = "Adminovic";
    private static final String ADMIN_ROOM = "Adminovic";
    private static final String ADMIN_GROUP = "Adminovic";
    private static final String ADMIN_EMAIL_ENC = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_2 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_2 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_3 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_2 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_2 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_2 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_2 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_3 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_4 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_3 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_3 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_3 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_3 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_4 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_5 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_4 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_4 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_4 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_4 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_5 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_6 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_5 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_5 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_5 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_5 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_6 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_7 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_6 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_6 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_6 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_6 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_7 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_8 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_7 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_7 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_7 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_7 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_8 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_9 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_8 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_8 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_8 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_8 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_9 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_10 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_9 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_9 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_9 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_9 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_10 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_11 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_10 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_10 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_10 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_10 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_11 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_12 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_11 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_11 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_11 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_11 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_12 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_13 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_12 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_12 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_12 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_12 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_13 = "QWRtaW5AY2hhdC5jb20=";
    private static final String ADMIN_PASSWORD_ENC_14 = "<PASSWORD>";
    private static final String ADMIN_NAME_ENC_13 = "QWRtaW4=";
    private static final String ADMIN_SURNAME_ENC_13 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_ROOM_ENC_13 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_GROUP_ENC_13 = "QWRtaW5vd2NpYw==";
    private static final String ADMIN_EMAIL_ENC_14 = "QWRtaW5AY2hhdC5jb20=";
    private