// ModernChatServer_4Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#changeAdminPassword(String, String, String)} method.
*/
class ModernChatServer_4Test {

    private static final String adminEmail = "<EMAIL>";
    private static final String adminPassword = "<PASSWORD>";
    private static final String newAdminPassword = "<PASSWORD>";
    private static final String newAdminPassword2 = "<PASSWORD>";
    private static final String newAdminPassword3 = "<PASSWORD>";
    private static final String newAdminPassword4 = "<PASSWORD>";
    private static final String newAdminPassword5 = "<PASSWORD>";
    private static final String newAdminPassword6 = "<PASSWORD>";
    private static final String newAdminPassword7 = "<PASSWORD>";
    private static final String newAdminPassword8 = "<PASSWORD>";
    private static final String newAdminPassword9 = "<PASSWORD>";
    private static final String newAdminPassword10 = "<PASSWORD>";
    private static final String newAdminPassword11 = "<PASSWORD>";
    private static final String newAdminPassword12 = "<PASSWORD>";
    private static final String newAdminPassword13 = "<PASSWORD>";
    private static final String newAdminPassword14 = "<PASSWORD>";
    private static final String newAdminPassword15 = "<PASSWORD>";
    private static final String newAdminPassword16 = "<PASSWORD>";
    private static final String newAdminPassword17 = "<PASSWORD>";
    private static final String newAdminPassword18 = "<PASSWORD>";
    private static final String newAdminPassword19 = "<PASSWORD>";
    private static final String newAdminPassword20 = "<PASSWORD>";
    private static final String newAdminPassword21 = "<PASSWORD>";
    private static final String newAdminPassword22 = "<PASSWORD>";
    private static final String newAdminPassword23 = "<PASSWORD>";
    private static final String newAdminPassword24 = "<PASSWORD>";
    private static final String newAdminPassword25 = "<PASSWORD>";
    private static final String newAdminPassword26 = "<PASSWORD>";
    private static final String newAdminPassword27 = "<PASSWORD>";
    private static final String newAdminPassword28 = "<PASSWORD>";
    private static final String newAdminPassword29 = "<PASSWORD>";
    private static final String newAdminPassword30 = "<PASSWORD>";
    private static final String newAdminPassword31 = "<PASSWORD>";
    private static final String newAdminPassword32 = "<PASSWORD>";
    private static final String newAdminPassword33 = "<PASSWORD>";
    private static final String newAdminPassword34 = "<PASSWORD>";
    private static final String newAdminPassword35 = "<PASSWORD>";
    private static final String newAdminPassword36 = "<PASSWORD>";
    private static final String newAdminPassword37 = "<PASSWORD>";
    private static final String newAdminPassword38 = "<PASSWORD>";
    private static final String newAdminPassword39 = "<PASSWORD>";
    private static final String newAdminPassword40 = "<PASSWORD>";
    private static final String newAdminPassword41 = "<PASSWORD>";
    private static final String newAdminPassword42 = "<PASSWORD>";
    private static final String newAdminPassword43 = "<PASSWORD>";
    private static final String newAdminPassword44 = "<PASSWORD>";
    private static final String newAdminPassword45 = "<PASSWORD>";
    private static final String newAdminPassword46 = "<PASSWORD>";
    private static final String newAdminPassword47 = "<PASSWORD>";
    private static final String newAdminPassword48 = "<PASSWORD>";
    private static final String newAdminPassword49 = "<PASSWORD>";
    private static final String newAdminPassword50 = "<PASSWORD>";
    private static final String newAdminPassword51 = "<PASSWORD>";
    private static final String newAdminPassword52 = "<PASSWORD>";
    private static final String newAdminPassword53 = "<PASSWORD>";
    private static final String newAdminPassword54 = "<PASSWORD>";
    private static final String newAdminPassword55 = "<PASSWORD>";
    private static final String newAdminPassword56 = "<PASSWORD>";
    private static final String newAdminPassword57 = "<PASSWORD>";
    private static final String newAdminPassword58 = "<PASSWORD>";
    private static final String newAdminPassword59 = "<PASSWORD>";
    private static final String newAdminPassword60 = "<PASSWORD>";
    private static final String newAdminPassword61 = "<PASSWORD>";
    private static final String newAdminPassword62 = "<PASSWORD>";
    private static final String newAdminPassword63 = "<PASSWORD>";
    private static final String newAdminPassword64 = "<PASSWORD>";
    private static final String newAdminPassword65 = "<PASSWORD>";
    private static final String newAdminPassword66 = "<PASSWORD>";
    private static final String newAdminPassword67 = "<PASSWORD>";
    private static final String newAdminPassword68 = "<PASSWORD>";
    private static final String newAdminPassword69 = "<PASSWORD>";
    private static final String newAdminPassword70 = "<PASSWORD>";
    private static final String newAdminPassword71 = "<PASSWORD>";
    private static final String newAdminPassword72 = "<PASSWORD>";
    private static final String newAdminPassword73 = "<PASSWORD>";
    private static final String newAdminPassword74 = "<PASSWORD>";
    private static final String newAdminPassword75 = "<PASSWORD>";
    private static final String newAdminPassword76 = "<PASSWORD>";
    private static final String newAdminPassword77 = "<PASSWORD>";
    private static final String newAdminPassword78 = "<PASSWORD>";
    private static final String newAdminPassword79 = "<PASSWORD>";
    private static final String newAdminPassword80 = "<PASSWORD>";
    private static final String newAdminPassword81 = "<PASSWORD>";
    private static final String newAdminPassword82 = "<PASSWORD>";
    private static final String newAdminPassword83 = "<PASSWORD>";
    private static final String newAdminPassword84 = "<PASSWORD>";
    private static final String newAdminPassword85 = "<PASSWORD>";
    private static final String newAdminPassword86 = "<PASSWORD>";
    private static final String newAdminPassword87 = "<PASSWORD>";
    private static final String newAdminPassword88 = "<PASSWORD>";
    private static final String newAdminPassword89 = "<PASSWORD>";
    private static final String newAdminPassword90 = "<PASSWORD>";
    private static final String newAdminPassword91 = "<PASSWORD>";
    private static final String newAdminPassword92 = "<PASSWORD>";
    private static final String newAdminPassword93 = "<PASSWORD>";
    private static final String newAdminPassword94 = "<PASSWORD>";
    private static final String newAdminPassword95 = "<PASSWORD>";
    private static final String newAdminPassword96 = "<PASSWORD>";
    private static final String newAdminPassword97 = "<PASSWORD>";
    private static final String newAdminPassword98 = "<PASSWORD>";
    private static final String newAdminPassword99 = "<PASSWORD>";
    private static final String newAdminPassword100 = "<PASSWORD>";
    private static final String newAdminPassword101 = "<PASSWORD>";
    private static final String newAdminPassword102 = "<PASSWORD>";
    private static final String newAdminPassword103 = "<PASSWORD>";
    private static final String newAdminPassword104 = "<PASSWORD>";
    private static final String newAdminPassword105 = "<PASSWORD>";
    private static final String newAdminPassword106 = "<PASSWORD>";
    private static final String newAdminPassword107 = "<PASSWORD>";
    private static final String newAdminPassword108 = "<PASSWORD>";
    private static final String newAdminPassword109 = "<PASSWORD>";
    private static final String newAdminPassword110 = "<PASSWORD>";
    private static final String newAdminPassword111 = "<PASSWORD>";
    private static final String newAdminPassword112 = "<PASSWORD>";
    private static final String newAdminPassword113 = "<PASSWORD>";
    private static final String newAdminPassword114 = "<PASSWORD>";
    private static final String newAdminPassword115 = "<PASSWORD>";
    private static final String newAdminPassword116 = "<PASSWORD>";
    private static final String newAdminPassword117 = "<PASSWORD>";
    private static final String newAdminPassword118 = "<PASSWORD>";
    private static final String newAdminPassword119 = "<PASSWORD>";
    private static final String newAdminPassword120 = "<PASSWORD>";
    private static final String newAdminPassword121 = "<PASSWORD>";
    private static final String newAdminPassword122 = "<PASSWORD>";
    private static final String newAdminPassword123 = "<PASSWORD>";
    private static final String newAdminPassword124 = "<PASSWORD>";
    private static final String newAdminPassword125 = "<PASSWORD>";
    private static final String newAdminPassword126 = "<PASSWORD>";
    private static final String newAdminPassword127 = "<PASSWORD>";
    private static final String newAdminPassword128 = "<PASSWORD>";
    private static final String newAdminPassword129 = "<PASSWORD>";
    private static final String newAdminPassword130 = "<PASSWORD>";
    private static final String newAdminPassword131 = "<PASSWORD>";
    private static final String newAdminPassword132 = "<PASSWORD>";
    private static final String newAdminPassword133 = "<PASSWORD>";
    private static final String newAdminPassword134 = "<PASSWORD>";
    private static final String newAdminPassword135 = "<PASSWORD>";
    private static final String newAdminPassword136 = "<PASSWORD>";
    private static final String newAdminPassword137 = "<PASSWORD>";
    private static final String newAdminPassword138 = "<PASSWORD>";
    private static final String newAdminPassword139 = "<PASSWORD>";
    private