// HttpActionClient_1Test.java
package net.sourceforge.jwbf.core.actions;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.JWBF;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.CookieException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import org.apache.http.HttpHost;
import org.apache.http.HttpResponse;
import org.apache.http.HttpStatus;
import org.apache.http.StatusLine;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.client.params.ClientPNames;
import org.apache.http.cookie.Cookie;
import org.apache.http.entity.mime.MultipartEntity;
import org.apache.http.entity.mime.content.FileBody;
import org.apache.http.entity.mime.content.StringBody;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.params.HttpParams;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link HttpActionClient}.
* It contains ten unit test cases for the {@link HttpActionClient#get(Get)} method.
*/
class HttpActionClient_1Test {

    private static final String URL = "http://www.google.de";
    private static final String USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.0) Gecko/20100101 Firefox/25.0";
    private static final String REFERER = "http://www.google.de";
    private static final String COOKIE = "name=value";
    private static final String POST_DATA = "name=value";
    private static final String POST_FILE = "test.txt";
    private static final String POST_FILE_CONTENT = "test";
    private static final String POST_FILE_CONTENT_2 = "test2";
    private static final String POST_FILE_CONTENT_3 = "test3";
    private static final String POST_FILE_CONTENT_4 = "test4";
    private static final String POST_FILE_CONTENT_5 = "test5";
    private static final String POST_FILE_CONTENT_6 = "test6";
    private static final String POST_FILE_CONTENT_7 = "test7";
    private static final String POST_FILE_CONTENT_8 = "test8";
    private static final String POST_FILE_CONTENT_9 = "test9";
    private static final String POST_FILE_CONTENT_10 = "test10";
    private static final String POST_FILE_CONTENT_11 = "test11";
    private static final String POST_FILE_CONTENT_12 = "test12";
    private static final String POST_FILE_CONTENT_13 = "test13";
    private static final String POST_FILE_CONTENT_14 = "test14";
    private static final String POST_FILE_CONTENT_15 = "test15";
    private static final String POST_FILE_CONTENT_16 = "test16";
    private static final String POST_FILE_CONTENT_17 = "test17";
    private static final String POST_FILE_CONTENT_18 = "test18";
    private static final String POST_FILE_CONTENT_19 = "test19";
    private static final String POST_FILE_CONTENT_20 = "test20";
    private static final String POST_FILE_CONTENT_21 = "test21";
    private static final String POST_FILE_CONTENT_22 = "test22";
    private static final String POST_FILE_CONTENT_23 = "test23";
    private static final String POST_FILE_CONTENT_24 = "test24";
    private static final String POST_FILE_CONTENT_25 = "test25";
    private static final String POST_FILE_CONTENT_26 = "test26";
    private static final String POST_FILE_CONTENT_27 = "test27";
    private static final String POST_FILE_CONTENT_28 = "test28";
    private static final String POST_FILE_CONTENT_29 = "test29";
    private static final String POST_FILE_CONTENT_30 = "test30";
    private static final String POST_FILE_CONTENT_31 = "test31";
    private static final String POST_FILE_CONTENT_32 = "test32";
    private static final String POST_FILE_CONTENT_33 = "test33";
    private static final String POST_FILE_CONTENT_34 = "test34";
    private static final String POST_FILE_CONTENT_35 = "test35";
    private static final String POST_FILE_CONTENT_36 = "test36";
    private static final String POST_FILE_CONTENT_37 = "test37";
    private static final String POST_FILE_CONTENT_38 = "test38";
    private static final String POST_FILE_CONTENT_39 = "test39";
    private static final String POST_FILE_CONTENT_40 = "test40";
    private static final String POST_FILE_CONTENT_41 = "test41";
    private static final String POST_FILE_CONTENT_42 = "test42";
    private static final String POST_FILE_CONTENT_43 = "test43";
    private static final String POST_FILE_CONTENT_44 = "test44";
    private static final String POST_FILE_CONTENT_45 = "test45";
    private static final String POST_FILE_CONTENT_46 = "test46";
    private static final String POST_FILE_CONTENT_47 = "test47";
    private static final String POST_FILE_CONTENT_48 = "test48";
    private static final String POST_FILE_CONTENT_49 = "test49";
    private static final String POST_FILE_CONTENT_50 = "test50";
    private static final String POST_FILE_CONTENT_51 = "test51";
    private static final String POST_FILE_CONTENT_52 = "test52";
    private static final String POST_FILE_CONTENT_53 = "test53";
    private static final String POST_FILE_CONTENT_54 = "test54";
    private static final String POST_FILE_CONTENT_55 = "test55";
    private static final String POST_FILE_CONTENT_56 = "test56";
    private static final String POST_FILE_CONTENT_57 = "test57";
    private static final String POST_FILE_CONTENT_58 = "test58";
    private static final String POST_FILE_CONTENT_59 = "test59";
    private static final String POST_FILE_CONTENT_60 = "test60";
    private static final String POST_FILE_CONTENT_61 = "test61";
    private static final String POST_FILE_CONTENT_62 = "test62";
    private static final String POST_FILE_CONTENT_63 = "test63";
    private static final String POST_FILE_CONTENT_64 = "test64";
    private static final String POST_FILE_CONTENT_65 = "test65";
    private static final String POST_FILE_CONTENT_66 = "test66";
    private static final String POST_FILE_CONTENT_67 = "test67";
    private static final String POST_FILE_CONTENT_68 = "test68";
    private static final String POST_FILE_CONTENT_69 = "test69";
    private static final String POST_FILE_CONTENT_70 = "test70";
    private static final String POST_FILE_CONTENT_71 = "test71";
    private static final String POST_FILE_CONTENT_72 = "test72";
    private static final String POST_FILE_CONTENT_73 = "test73";
    private static final String POST_FILE_CONTENT_74 = "test74";
    private static final String POST_FILE_CONTENT_75 = "test75";
    private static final String POST_FILE_CONTENT_76 = "test76";
    private static final String POST_FILE_CONTENT_77 = "test77";
    private static final String POST_FILE_CONTENT_78 = "test78";
    private static final String POST_FILE_CONTENT_79 = "test79";
    private static final String POST_FILE_CONTENT_80 = "test80";
    private static final String POST_FILE_CONTENT_81 = "test81";
    private static final String POST_FILE_CONTENT_82 = "test82";
    private static final String POST_FILE_CONTENT_83 = "test83";
    private static final String POST_FILE_CONTENT_84 = "test84";
    private static final String POST_FILE_CONTENT_85 = "test85";
    private static final String POST_FILE_CONTENT_86 = "test86";
    private static final String POST_FILE_CONTENT_87 = "test87";
    private static final String POST_FILE_CONTENT_88 = "test88";
    private static final String POST_FILE_CONTENT_89 = "test89";
    private static final String POST_FILE_CONTENT_90 = "test90";
    private static final String POST_FILE_CONTENT_91 = "test91";
    private static final String POST_FILE_CONTENT_92 = "test92";
    private static final String POST_FILE_CONTENT_93 = "test93";
    private static final String POST_FILE_CONTENT_94 = "test94";
    private static final String POST_FILE_CONTENT_95 = "test95";
    private static final String POST_FILE_CONTENT_96 = "test96";
    private static final String POST_FILE_CONTENT_97 = "test97";
    private static final String POST_FILE_CONTENT_98 = "test98";
    private static final String POST_FILE_CONTENT_99 = "test99";
    private static final String POST_FILE_CONTENT_100 =