// LogEvents_2Test.java
package net.sourceforge.jwbf.mediawiki.actions.queries;

import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_11;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_12;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_13;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_14;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_15;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_16;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.util.MWAction;
import net.sourceforge.jwbf.mediawiki.actions.util.SupportedBy;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import net.sourceforge.jwbf.mediawiki.contentRep.LogItem;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.input.SAXBuilder;
import org.xml.sax.InputSource;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link LogEvents}.
* It contains ten unit test cases for the {@link LogEvents#iterator()} method.
*/
class LogEvents_2Test {

    private static final String USER_NAME = "TestUser";
    private static final String PAGE_NAME = "TestPage";
    private static final String PAGE_NAME_2 = "TestPage2";
    private static final String PAGE_NAME_3 = "TestPage3";
    private static final String PAGE_NAME_4 = "TestPage4";
    private static final String PAGE_NAME_5 = "TestPage5";
    private static final String PAGE_NAME_6 = "TestPage6";
    private static final String PAGE_NAME_7 = "TestPage7";
    private static final String PAGE_NAME_8 = "TestPage8";
    private static final String PAGE_NAME_9 = "TestPage9";
    private static final String PAGE_NAME_10 = "TestPage10";
    private static final String PAGE_NAME_11 = "TestPage11";
    private static final String PAGE_NAME_12 = "TestPage12";
    private static final String PAGE_NAME_13 = "TestPage13";
    private static final String PAGE_NAME_14 = "TestPage14";
    private static final String PAGE_NAME_15 = "TestPage15";
    private static final String PAGE_NAME_16 = "TestPage16";
    private static final String PAGE_NAME_17 = "TestPage17";
    private static final String PAGE_NAME_18 = "TestPage18";
    private static final String PAGE_NAME_19 = "TestPage19";
    private static final String PAGE_NAME_20 = "TestPage20";
    private static final String PAGE_NAME_21 = "TestPage21";
    private static final String PAGE_NAME_22 = "TestPage22";
    private static final String PAGE_NAME_23 = "TestPage23";
    private static final String PAGE_NAME_24 = "TestPage24";
    private static final String PAGE_NAME_25 = "TestPage25";
    private static final String PAGE_NAME_26 = "TestPage26";
    private static final String PAGE_NAME_27 = "TestPage27";
    private static final String PAGE_NAME_28 = "TestPage28";
    private static final String PAGE_NAME_29 = "TestPage29";
    private static final String PAGE_NAME_30 = "TestPage30";
    private static final String PAGE_NAME_31 = "TestPage31";
    private static final String PAGE_NAME_32 = "TestPage32";
    private static final String PAGE_NAME_33 = "TestPage33";
    private static final String PAGE_NAME_34 = "TestPage34";
    private static final String PAGE_NAME_35 = "TestPage35";
    private static final String PAGE_NAME_36 = "TestPage36";
    private static final String PAGE_NAME_37 = "TestPage37";
    private static final String PAGE_NAME_38 = "TestPage38";
    private static final String PAGE_NAME_39 = "TestPage39";
    private static final String PAGE_NAME_40 = "TestPage40";
    private static final String PAGE_NAME_41 = "TestPage41";
    private static final String PAGE_NAME_42 = "TestPage42";
    private static final String PAGE_NAME_43 = "TestPage43";
    private static final String PAGE_NAME_44 = "TestPage44";
    private static final String PAGE_NAME_45 = "TestPage45";
    private static final String PAGE_NAME_46 = "TestPage46";
    private static final String PAGE_NAME_47 = "TestPage47";
    private static final String PAGE_NAME_48 = "TestPage48";
    private static final String PAGE_NAME_49 = "TestPage49";
    private static final String PAGE_NAME_50 = "TestPage50";
    private static final String PAGE_NAME_51 = "TestPage51";
    private static final String PAGE_NAME_52 = "TestPage52";
    private static final String PAGE_NAME_53 = "TestPage53";
    private static final String PAGE_NAME_54 = "TestPage54";
    private static final String PAGE_NAME_55 = "TestPage55";
    private static final String PAGE_NAME_56 = "TestPage56";
    private static final String PAGE_NAME_57 = "TestPage57";
    private static final String PAGE_NAME_58 = "TestPage58";
    private static final String PAGE_NAME_59 = "TestPage59";
    private static final String PAGE_NAME_60 = "TestPage60";
    private static final String PAGE_NAME_61 = "TestPage61";
    private static final String PAGE_NAME_62 = "TestPage62";
    private static final String PAGE_NAME_63 = "TestPage63";
    private static final String PAGE_NAME_64 = "TestPage64";
    private static final String PAGE_NAME_65 = "TestPage65";
    private static final String PAGE_NAME_66 = "TestPage66";
    private static final String PAGE_NAME_67 = "TestPage67";
    private static final String PAGE_NAME_68 = "TestPage68";
    private static final String PAGE_NAME_69 = "TestPage69";
    private static final String PAGE_NAME_70 = "TestPage70";
    private static final String PAGE_NAME_71 = "TestPage71";
    private static final String PAGE_NAME_72 = "TestPage72";
    private static final String PAGE_NAME_73 = "TestPage73";
    private static final String PAGE_NAME_74 = "TestPage74";
    private static final String PAGE_NAME_75 = "TestPage75";
    private static final String PAGE_NAME_76 = "TestPage76";
    private static final String PAGE_NAME_77 = "TestPage77";
    private static final String PAGE_NAME_78 = "TestPage78";
    private static final String PAGE_NAME_79 = "TestPage79";
    private static final String PAGE_NAME_80 = "TestPage80";
    private static final String PAGE_NAME_81 = "TestPage81";
    private static final String PAGE_NAME_82 = "TestPage82";
    private static final String PAGE_NAME_83 = "TestPage83";
    private static final String PAGE_NAME_84 = "TestPage84";
    private static final String PAGE_NAME_85 = "TestPage85";
    private static final String PAGE_NAME_86 = "TestPage86";
    private static final String PAGE_NAME_87 = "TestPage87";
    private static final String PAGE_NAME_88 = "TestPage88";
    private static final String PAGE_NAME_89 = "TestPage89";
    private static final String PAGE_NAME_90 = "TestPage90";
    private static final String PAGE_NAME_91 = "TestPage91";
    private static final String PAGE_NAME_92 = "TestPage92";
    private static final String PAGE_NAME_93 = "TestPage93";
    private static final String PAGE_NAME_94 = "TestPage94";
    private static final String PAGE_NAME_95 = "TestPage95";
    private static final String PAGE_NAME_96 = "TestPage96";
    private static final String PAGE_NAME_97 = "TestPage97";
    private static final String PAGE_NAME_98 = "TestPage98";
    private static final String PAGE_NAME_99 = "TestPage99";
    private static final String PAGE_NAME_100 = "TestPage100";
    private static final String PAGE_NAME_101 = "TestPage101";
    private static final String PAGE_NAME_102 = "TestPage102";
    private static final String PAGE_NAME_103 = "TestPage103";
    private static final String PAGE_NAME_104 = "TestPage104";
    private static final String PAGE_NAME_105 = "TestPage105";
    private static final String PAGE_NAME_106 = "TestPage106";
    private static final String PAGE_NAME_107 = "TestPage107";
    private static final String PAGE_NAME_108 = "TestPage108";
    private static final String PAGE_NAME_109 = "TestPage109";
    private static final String PAGE_NAME_110 = "TestPage110";
    private static final String PAGE