// _GetEngineResponse_1Test.java
package mygrid.web;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link _GetEngineResponse}.
* It contains ten unit test cases for the {@link _GetEngineResponse#getTypeDesc()} method.
*/
class _GetEngineResponse_1Test {

	/**
	* Test case for the {@link _GetEngineResponse#getTypeDesc()} method.
	*
	* @throws Exception
	* 		Thrown if the test fails for some reason.
	*/
	@Test
	void testGetTypeDesc_1()
	throws Exception {
		_GetEngineResponse fixture = new _GetEngineResponse();
		fixture.getEngineResult = new Engine();

		org.apache.axis.description.TypeDesc result = fixture.getTypeDesc();

		// add additional test code here
		assertNotNull(result);
		assertEquals("org.apache.axis.description.TypeDesc@1f8f8f8f", result.toString());
		assertEquals(false, result.isElement());
		assertEquals(false, result.isSimpleType());
		assertEquals(false, result.isAbstract());
		assertEquals(false, result.isArray());
		assertEquals(false, result.isAttachment());
		assertEquals(false, result.isBaseType());
		assertEquals(false, result.isEnum());
		assertEquals(false, result.isExtensibleElements());
		assertEquals(false, result.isExtension());
		assertEquals(false, result.isLiteralArray());
		assertEquals(false, result.isLiteralElement());
		assertEquals(false, result.isLiteralType());
		assertEquals(false, result.isNillable());
		assertEquals(false, result.isRpc());
		assertEquals(false, result.isSchemaType());
		assertEquals(false, result.isSimpleContent());
		assertEquals(false, result.isSimpleLiteral());
		assertEquals(false, result.isSoapArray());
		assertEquals(false, result.isSoapEncoded());
		assertEquals(false, result.isSoapType());
		assertEquals(false, result.isUnknown());
		assertEquals(false, result.isURType());
		assertEquals(false, result.isXMLType());
		assertEquals(false, result.isWrapped());
		assertEquals(false, result.isWrapperElement());
		assertEquals(false, result.isWrapperType());
		assertEquals(false, result.isXmlJavaTypeAdapter());
		assertEquals(false, result.isXmlList());
		assertEquals(false, result.isXmlSchemaType());
		assertEquals(false, result.isXmlWildcard());
		assertEquals(false, result.isXmlany());
		assertEquals(false, result.isXmlanyAttribute());
		assertEquals(false, result.isXmlattachmentref());
		assertEquals(false, result.isXmlattribute());
		assertEquals(false, result.isXmlchoice());
		assertEquals(false, result.isXmlelement());
		assertEquals(false, result.isXmlmixed());
		assertEquals(false, result.isXmlroot());
		assertEquals(false, result.isXmltype());
		assertEquals(false, result.isXmlvalueref());
		assertEquals(false, result.isXmlwildcard());
		assertEquals(false, result.isXmlwsdlarraytype());
		assertEquals(false, result.isXmlwsdlarraytypeArray());
		assertEquals(false, result.isXmlwsdlarraytypeList());
		assertEquals(false, result.isXmlwsdlarraytypeRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesArray());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesList());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesRestriction());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnion());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypes());
		assertEquals(false, result.isXmlwsdlarraytypeUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMemberTypesUnionMember