// HtmlContentParser_1Test.java
package org.asphodel.parser;

import au.id.jericho.lib.html.Source;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.net.URL;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link HtmlContentParser}.
* It contains ten unit test cases for the {@link HtmlContentParser#extractText(Reader)} method.
*/
class HtmlContentParser_1Test {
private static Log log = LogFactory.getLog(HtmlContentParser_1Test.class);
		private static final String TEST_FILE_NAME = "test.html";
		private static final String TEST_FILE_NAME_1 = "test_1.html";
		private static final String TEST_FILE_NAME_2 = "test_2.html";
		private static final String TEST_FILE_NAME_3 = "test_3.html";
		private static final String TEST_FILE_NAME_4 = "test_4.html";
		private static final String TEST_FILE_NAME_5 = "test_5.html";
		private static final String TEST_FILE_NAME_6 = "test_6.html";
		private static final String TEST_FILE_NAME_7 = "test_7.html";
		private static final String TEST_FILE_NAME_8 = "test_8.html";
		private static final String TEST_FILE_NAME_9 = "test_9.html";
		private static final String TEST_FILE_NAME_10 = "test_10.html";
		private static final String TEST_FILE_NAME_11 = "test_11.html";
		private static final String TEST_FILE_NAME_12 = "test_12.html";
		private static final String TEST_FILE_NAME_13 = "test_13.html";
		private static final String TEST_FILE_NAME_14 = "test_14.html";
		private static final String TEST_FILE_NAME_15 = "test_15.html";
		private static final String TEST_FILE_NAME_16 = "test_16.html";
		private static final String TEST_FILE_NAME_17 = "test_17.html";
		private static final String TEST_FILE_NAME_18 = "test_18.html";
		private static final String TEST_FILE_NAME_19 = "test_19.html";
		private static final String TEST_FILE_NAME_20 = "test_20.html";
		private static final String TEST_FILE_NAME_21 = "test_21.html";
		private static final String TEST_FILE_NAME_22 = "test_22.html";
		private static final String TEST_FILE_NAME_23 = "test_23.html";
		private static final String TEST_FILE_NAME_24 = "test_24.html";
		private static final String TEST_FILE_NAME_25 = "test_25.html";
		private static final String TEST_FILE_NAME_26 = "test_26.html";
		private static final String TEST_FILE_NAME_27 = "test_27.html";
		private static final String TEST_FILE_NAME_28 = "test_28.html";
		private static final String TEST_FILE_NAME_29 = "test_29.html";
		private static final String TEST_FILE_NAME_30 = "test_30.html";
		private static final String TEST_FILE_NAME_31 = "test_31.html";
		private static final String TEST_FILE_NAME_32 = "test_32.html";
		private static final String TEST_FILE_NAME_33 = "test_33.html";
		private static final String TEST_FILE_NAME_34 = "test_34.html";
		private static final String TEST_FILE_NAME_35 = "test_35.html";
		private static final String TEST_FILE_NAME_36 = "test_36.html";
		private static final String TEST_FILE_NAME_37 = "test_37.html";
		private static final String TEST_FILE_NAME_38 = "test_38.html";
		private static final String TEST_FILE_NAME_39 = "test_39.html";
		private static final String TEST_FILE_NAME_40 = "test_40.html";
		private static final String TEST_FILE_NAME_41 = "test_41.html";
		private static final String TEST_FILE_NAME_42 = "test_42.html";
		private static final String TEST_FILE_NAME_43 = "test_43.html";
		private static final String TEST_FILE_NAME_44 = "test_44.html";
		private static final String TEST_FILE_NAME_45 = "test_45.html";
		private static final String TEST_FILE_NAME_46 = "test_46.html";
		private static final String TEST_FILE_NAME_47 = "test_47.html";
		private static final String TEST_FILE_NAME_48 = "test_48.html";
		private static final String TEST_FILE_NAME_49 = "test_49.html";
		private static final String TEST_FILE_NAME_50 = "test_50.html";
		private static final String TEST_FILE_NAME_51 = "test_51.html";
		private static final String TEST_FILE_NAME_52 = "test_52.html";
		private static final String TEST_FILE_NAME_53 = "test_53.html";
		private static final String TEST_FILE_NAME_54 = "test_54.html";
		private static final String TEST_FILE_NAME_55 = "test_55.html";
		private static final String TEST_FILE_NAME_56 = "test_56.html";
		private static final String TEST_FILE_NAME_57 = "test_57.html";
		private static final String TEST_FILE_NAME_58 = "test_58.html";
		private static final String TEST_FILE_NAME_59 = "test_59.html";
		private static final String TEST_FILE_NAME_60 = "test_60.html";
		private static final String TEST_FILE_NAME_61 = "test_61.html";
		private static final String TEST_FILE_NAME_62 = "test_62.html";
		private static final String TEST_FILE_NAME_63 = "test_63.html";
		private static final String TEST_FILE_NAME_64 = "test_64.html";
		private static final String TEST_FILE_NAME_65 = "test_65.html";
		private static final String TEST_FILE_NAME_66 = "test_66.html";
		private static final String TEST_FILE_NAME_67 = "test_67.html";
		private static final String TEST_FILE_NAME_68 = "test_68.html";
		private static final String TEST_FILE_NAME_69 = "test_69.html";
		private static final String TEST_FILE_NAME_70 = "test_70.html";
		private static final String TEST_FILE_NAME_71 = "test_71.html";
		private static final String TEST_FILE_NAME_72 = "test_72.html";
		private static final String TEST_FILE_NAME_73 = "test_73.html";
		private static final String TEST_FILE_NAME_74 = "test_74.html";
		private static final String TEST_FILE_NAME_75 = "test_75.html";
		private static final String TEST_FILE_NAME_76 = "test_76.html";
		private static final String TEST_FILE_NAME_77 = "test_77.html";
		private static final String TEST_FILE_NAME_78 = "test_78.html";
		private static final String TEST_FILE_NAME_79 = "test_79.html";
		private static final String TEST_FILE_NAME_80 = "test_80.html";
		private static final String TEST_FILE_NAME_81 = "test_81.html";
		private static final String TEST_FILE_NAME_82 = "test_82.html";
		private static final String TEST_FILE_NAME_83 = "test_83.html";
		private static final String TEST_FILE_NAME_84 = "test_84.html";
		private static final String TEST_FILE_NAME_85 = "test_85.html";
		private static final String TEST_FILE_NAME_86 = "test_86.html";
		private static final String TEST_FILE_NAME_87 = "test_87.html";
		private static final String TEST_FILE_NAME_88 = "test_88.html";
		private static final String TEST_FILE_NAME_89 = "test_89.html";
		