/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:58:27 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Add;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Add_ESTest extends Add_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Add.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = Add.add(0, (-1543));
      assertEquals((-1543), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Add.add(3214, (-1543));
      assertEquals(1671, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Add add0 = new Add();
  }
}
