/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:42:29 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.AntiShuffle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AntiShuffle_ESTest extends AntiShuffle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = AntiShuffle.antiShuffle("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        AntiShuffle.antiShuffle((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.AntiShuffle", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = AntiShuffle.antiShuffle("original.AntiShuffle");
      assertEquals(".ASaeffghiiillnnortu", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AntiShuffle antiShuffle0 = new AntiShuffle();
  }
}
