/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:28:51 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Bf;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Bf_ESTest extends Bf_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = Bf.bf("Saturn", "Saturn");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = Bf.bf("Mercury", "Saturn");
      assertEquals(4, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = Bf.bf("Uranus", "Mercury");
      assertEquals(5, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = Bf.bf("Mercury", "n1&aT:+^-4OJ'");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = Bf.bf("n1&aT:+^-4OJ'", "Mercury");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Bf bf0 = new Bf();
  }
}
