/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:37:14 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Stream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.CanArrange;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CanArrange_ESTest extends CanArrange_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-759));
      linkedList0.add((Object) integer0);
      Integer integer1 = new Integer(1069);
      linkedList0.add((Object) integer1);
      int int0 = CanArrange.canArrange(linkedList0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-4147));
      linkedList0.add((Object) integer0);
      linkedList0.add((Object) integer0);
      linkedList0.add((Object) integer0);
      int int0 = CanArrange.canArrange(linkedList0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(0);
      List<Object> list0 = linkedList0.subList(0, 0);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        CanArrange.canArrange(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-4147));
      linkedList0.add((Object) null);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        CanArrange.canArrange(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.CanArrange", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Stream<Object> stream0 = linkedList0.parallelStream();
      linkedList0.add((Object) stream0);
      Integer integer0 = new Integer(0);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        CanArrange.canArrange(linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.util.stream.ReferencePipeline$Head cannot be cast to java.lang.Integer
         //
         verifyException("original.CanArrange", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(8);
      linkedList0.push(integer0);
      Integer integer1 = new Integer(6);
      linkedList0.add((Object) integer1);
      int int0 = CanArrange.canArrange(linkedList0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CanArrange canArrange0 = new CanArrange();
  }
}
