/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:35:32 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.ChooseNum;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChooseNum_ESTest extends ChooseNum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChooseNum.chooseNum((-3509), 2142);
      // Undeclared exception!
      ChooseNum.chooseNum((-3509), 927);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = ChooseNum.chooseNum((-1), 1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = ChooseNum.chooseNum((-566), (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChooseNum chooseNum0 = new ChooseNum();
  }
}
