/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:17:22 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.CircularShift;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CircularShift_ESTest extends CircularShift_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        CircularShift.circularShift((-2145), (-2145));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = CircularShift.circularShift(1685, 1384);
      assertEquals("5861", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = CircularShift.circularShift(0, 1);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CircularShift circularShift0 = new CircularShift();
  }
}
