/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 18:57:42 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.DecimalToBinary;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DecimalToBinary_ESTest extends DecimalToBinary_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = DecimalToBinary.decimalToBinary((-1));
      assertEquals("dbdb", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = DecimalToBinary.decimalToBinary(0);
      assertEquals("db0db", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = DecimalToBinary.decimalToBinary(244);
      assertEquals("db11110100db", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DecimalToBinary decimalToBinary0 = new DecimalToBinary();
  }
}
