/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:14:27 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.DoubleTheDifference;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DoubleTheDifference_ESTest extends DoubleTheDifference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(588289);
      linkedList0.add((Object) integer0);
      int int0 = DoubleTheDifference.doubleTheDifference(linkedList0);
      assertEquals((-1808403455), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = linkedList0.subList(0, 0);
      Integer integer0 = Integer.valueOf(0);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        DoubleTheDifference.doubleTheDifference(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        DoubleTheDifference.doubleTheDifference((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.DoubleTheDifference", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-1923));
      linkedList0.add((Object) integer0);
      int int0 = DoubleTheDifference.doubleTheDifference(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(844);
      linkedList0.add((Object) integer0);
      int int0 = DoubleTheDifference.doubleTheDifference(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      linkedList0.offerFirst(object0);
      int int0 = DoubleTheDifference.doubleTheDifference(linkedList0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(767);
      linkedList0.add((Object) integer0);
      int int0 = DoubleTheDifference.doubleTheDifference(linkedList0);
      assertEquals(588289, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DoubleTheDifference doubleTheDifference0 = new DoubleTheDifference();
  }
}
