/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:12:06 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.EvenOddPalindrome;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvenOddPalindrome_ESTest extends EvenOddPalindrome_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      EvenOddPalindrome.evenOddPalindrome(2999);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Integer> list0 = EvenOddPalindrome.evenOddPalindrome(586);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvenOddPalindrome evenOddPalindrome0 = new EvenOddPalindrome();
  }
}
