/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:22:15 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Fib;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Fib_ESTest extends Fib_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Fib.fib((-4470));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Fib.fib(8824);
      // Undeclared exception!
      Fib.fib(8824);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Fib fib0 = new Fib();
  }
}
