/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:16:13 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Fibfib;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Fibfib_ESTest extends Fibfib_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Fibfib.fibfib(8391);
      assertEquals((-578380819), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      Fibfib.fibfib(1938715234);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Fibfib.fibfib(456);
      assertEquals(229900568, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = Fibfib.fibfib(1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = Fibfib.fibfib(2);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Fibfib fibfib0 = new Fibfib();
  }
}
