/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:17:14 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.FizzBuzz;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FizzBuzz_ESTest extends FizzBuzz_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzz.fizzBuzz(6673);
      // Undeclared exception!
      FizzBuzz.fizzBuzz(6673);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = FizzBuzz.fizzBuzz(55);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = FizzBuzz.fizzBuzz(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FizzBuzz fizzBuzz0 = new FizzBuzz();
  }
}
