/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:54:12 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GenerateIntegers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GenerateIntegers_ESTest extends GenerateIntegers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Object> list0 = GenerateIntegers.generateIntegers(0, 0);
      assertFalse(list0.contains(0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = GenerateIntegers.generateIntegers((-304), 8);
      assertTrue(list0.contains(8));
      assertEquals(4, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GenerateIntegers generateIntegers0 = new GenerateIntegers();
  }
}
