/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:50:05 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetMaxTriples;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetMaxTriples_ESTest extends GetMaxTriples_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = GetMaxTriples.getMaxTriples(32);
      assertEquals(1495, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      GetMaxTriples.getMaxTriples(41);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = GetMaxTriples.getMaxTriples((-1949));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetMaxTriples getMaxTriples0 = new GetMaxTriples();
  }
}
