/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:31:06 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GetPositive;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GetPositive_ESTest extends GetPositive_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(0);
      linkedList0.addFirst(integer0);
      List<Object> list0 = GetPositive.getPositive(linkedList0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) null);
      List<Object> list0 = linkedList0.subList(1, 1);
      linkedList0.add((Object) list0);
      // Undeclared exception!
      try { 
        GetPositive.getPositive(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        GetPositive.getPositive((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.GetPositive", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(1068);
      linkedList0.add((Object) integer0);
      List<Object> list0 = GetPositive.getPositive(linkedList0);
      assertTrue(list0.contains(1068));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = Integer.valueOf((-1273));
      linkedList0.add((Object) integer0);
      List<Object> list0 = GetPositive.getPositive(linkedList0);
      assertFalse(list0.contains((-1273)));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GetPositive getPositive0 = new GetPositive();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) getPositive0);
      List<Object> list0 = GetPositive.getPositive(linkedList0);
      assertEquals(0, list0.size());
  }
}
