/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:41:25 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.GreatestCommonDivisor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GreatestCommonDivisor_ESTest extends GreatestCommonDivisor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor(702, 0);
      assertEquals(702, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = GreatestCommonDivisor.greatestCommonDivisor((-1698), (-1698));
      assertEquals((-1698), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
  }
}
