/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 23:03:36 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Histogram;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Histogram_ESTest extends Histogram_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMap hashMap0 = (HashMap)Histogram.histogram("");
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashMap hashMap0 = (HashMap)Histogram.histogram("  AdXa");
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HashMap hashMap0 = (HashMap)Histogram.histogram((String) null);
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Histogram histogram0 = new Histogram();
  }
}
