/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:32:33 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.IntToMiniRoman;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntToMiniRoman_ESTest extends IntToMiniRoman_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = IntToMiniRoman.intToMiniRoman(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = IntToMiniRoman.intToMiniRoman(5);
      assertEquals("v", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IntToMiniRoman intToMiniRoman0 = new IntToMiniRoman();
  }
}
