/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:40:52 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.IsMultiplyPrime;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IsMultiplyPrime_ESTest extends IsMultiplyPrime_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Boolean boolean0 = IsMultiplyPrime.isMultiplyPrime(1592);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IsMultiplyPrime.isMultiplyPrime(5227);
      // Undeclared exception!
      IsMultiplyPrime.isMultiplyPrime(5227);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Boolean boolean0 = IsMultiplyPrime.isMultiplyPrime(2318);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IsMultiplyPrime isMultiplyPrime0 = new IsMultiplyPrime();
  }
}
