/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:50:45 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.LargestPrimeFactor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LargestPrimeFactor_ESTest extends LargestPrimeFactor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LargestPrimeFactor.largestPrimeFactor(5737);
      // Undeclared exception!
      LargestPrimeFactor.largestPrimeFactor(5737);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = LargestPrimeFactor.largestPrimeFactor(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LargestPrimeFactor largestPrimeFactor0 = new LargestPrimeFactor();
  }
}
