/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:24:12 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.LargestDivisor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LargestDivisor_ESTest extends LargestDivisor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = LargestDivisor.largestDivisor(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LargestDivisor.largestDivisor(4193);
      LargestDivisor.largestDivisor(4193);
      // Undeclared exception!
      LargestDivisor.largestDivisor(4193);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = LargestDivisor.largestDivisor(0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LargestDivisor largestDivisor0 = new LargestDivisor();
  }
}
