/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:26:31 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MakeAPile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MakeAPile_ESTest extends MakeAPile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Integer> list0 = MakeAPile.makeAPile(0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MakeAPile.makeAPile(258);
      MakeAPile.makeAPile(2642);
      MakeAPile.makeAPile(2642);
      MakeAPile.makeAPile(2642);
      // Undeclared exception!
      MakeAPile.makeAPile(1838);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Integer> list0 = MakeAPile.makeAPile(1223);
      assertEquals(1223, list0.size());
      assertTrue(list0.contains(1223));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MakeAPile makeAPile0 = new MakeAPile();
  }
}
