/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:47:24 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MakePalindrome;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MakePalindrome_ESTest extends MakePalindrome_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = MakePalindrome.makePalindrome("^aOB6wF'8DHP8QxK{*R*{KxQ8PHD8'Fw6BOa^");
      assertNotNull(string0);
      assertEquals("^aOB6wF'8DHP8QxK{*R*{KxQ8PHD8'Fw6BOa^", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        MakePalindrome.makePalindrome((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.MakePalindrome", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = MakePalindrome.makePalindrome("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = MakePalindrome.makePalindrome("uo:)Gq7\t\"1{p3'~");
      assertEquals("uo:)Gq7\t\"1{p3'~'3p{1\"\t7qG):ou", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MakePalindrome makePalindrome0 = new MakePalindrome();
  }
}
