/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:00:56 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MaxFill;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MaxFill_ESTest extends MaxFill_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      linkedList0.add((List<Integer>) linkedList1);
      Integer integer0 = new Integer((-3435));
      linkedList1.addFirst(integer0);
      int int0 = MaxFill.maxFill(linkedList0, 666);
      assertEquals((-5), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      linkedList0.add((List<Integer>) null);
      // Undeclared exception!
      try { 
        MaxFill.maxFill(linkedList0, (-1279));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.MaxFill", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      linkedList0.add((List<Integer>) linkedList1);
      Integer integer0 = new Integer((-3435));
      linkedList1.addFirst(integer0);
      int int0 = MaxFill.maxFill(linkedList0, (-1));
      assertEquals(3435, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<List<Integer>> linkedList0 = new LinkedList<List<Integer>>();
      LinkedList<Integer> linkedList1 = new LinkedList<Integer>();
      linkedList0.add((List<Integer>) linkedList1);
      int int0 = MaxFill.maxFill(linkedList0, (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MaxFill maxFill0 = new MaxFill();
  }
}
