/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:52:48 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Maximum1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Maximum1_ESTest extends Maximum1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      Integer integer1 = new Integer(191);
      linkedList0.offer(integer1);
      Integer integer2 = new Integer(191);
      linkedList0.add(integer0);
      linkedList0.add(integer2);
      List<Object> list0 = Maximum1.maximum(linkedList0, 2);
      assertTrue(list0.contains(920));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(927);
      linkedList0.offer(integer0);
      Integer integer1 = new Integer((-891));
      linkedList0.add(integer1);
      List<Object> list0 = Maximum1.maximum(linkedList0, 1);
      assertEquals(1, list0.size());
      assertFalse(list0.contains((-891)));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      linkedList0.offer(integer0);
      linkedList0.add(integer0);
      linkedList0.add(integer0);
      List<Object> list0 = Maximum1.maximum(linkedList0, 1);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.add((Integer) null);
      List<Object> list0 = Maximum1.maximum(linkedList0, 1);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(1);
      linkedList0.offer(integer0);
      List<Integer> list0 = linkedList0.subList(1, 1);
      linkedList0.add(integer0);
      // Undeclared exception!
      try { 
        Maximum1.maximum(list0, 1);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.offer((Integer) null);
      linkedList0.add((Integer) null);
      // Undeclared exception!
      try { 
        Maximum1.maximum(linkedList0, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PriorityQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      linkedList0.offer(integer0);
      // Undeclared exception!
      try { 
        Maximum1.maximum(linkedList0, (-1045));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PriorityQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      Integer integer1 = new Integer(191);
      linkedList0.offer(integer1);
      linkedList0.add(integer0);
      linkedList0.add(integer0);
      List<Object> list0 = Maximum1.maximum(linkedList0, 2);
      assertEquals(2, list0.size());
      assertFalse(list0.contains(191));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      linkedList0.offer(integer0);
      List<Object> list0 = Maximum1.maximum(linkedList0, 687);
      assertTrue(list0.contains(920));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(920);
      linkedList0.offer(integer0);
      List<Object> list0 = Maximum1.maximum(linkedList0, 0);
      assertFalse(list0.contains(920));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      List<Object> list0 = Maximum1.maximum(linkedList0, 920);
      assertFalse(list0.contains(920));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Maximum1 maximum1_0 = new Maximum1();
  }
}
