/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:49:07 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.MoveOneBall;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MoveOneBall_ESTest extends MoveOneBall_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        MoveOneBall.moveOneBall((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.MoveOneBall", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      // Undeclared exception!
      try { 
        MoveOneBall.moveOneBall(linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.util.LinkedList cannot be cast to java.lang.Integer
         //
         verifyException("original.MoveOneBall", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(419);
      linkedList0.add((Object) integer0);
      Integer integer1 = new Integer((-135));
      linkedList0.add((Object) integer1);
      Integer integer2 = new Integer(1672);
      linkedList0.add((Object) integer2);
      Boolean boolean0 = MoveOneBall.moveOneBall(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(419);
      linkedList0.add((Object) integer0);
      Integer integer1 = new Integer((-135));
      linkedList0.add((Object) integer1);
      Boolean boolean0 = MoveOneBall.moveOneBall(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Boolean boolean0 = MoveOneBall.moveOneBall(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(419);
      linkedList0.add((Object) integer0);
      Boolean boolean0 = MoveOneBall.moveOneBall(linkedList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MoveOneBall moveOneBall0 = new MoveOneBall();
  }
}
