/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:15:48 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.NumericalLetterGrade;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NumericalLetterGrade_ESTest extends NumericalLetterGrade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(2.3);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(3.7);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Float float0 = new Float(1621.5022156);
      linkedList0.add((Number) float0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Long long0 = new Long(0L);
      List<Number> list0 = linkedList0.subList(0, 0);
      linkedList0.add((Number) long0);
      // Undeclared exception!
      try { 
        NumericalLetterGrade.numericalLetterGrade(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      linkedList0.add((Number) null);
      // Undeclared exception!
      try { 
        NumericalLetterGrade.numericalLetterGrade(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.NumericalLetterGrade", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Long long0 = new Long(0L);
      linkedList0.add((Number) long0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Integer integer0 = new Integer(1);
      linkedList0.add((Number) integer0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Float float0 = new Float(0.7);
      linkedList0.add((Number) float0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(1.7);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(2.0);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(2.7);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(3.0);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(3.3);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Float float0 = new Float(3.7);
      linkedList0.add((Number) float0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(4.0);
      linkedList0.add((Number) double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      Double double0 = new Double(1.3);
      linkedList0.push(double0);
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Number> linkedList0 = new LinkedList<Number>();
      List<String> list0 = NumericalLetterGrade.numericalLetterGrade(linkedList0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      NumericalLetterGrade numericalLetterGrade0 = new NumericalLetterGrade();
  }
}
