/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:08:37 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.PrimeFib;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PrimeFib_ESTest extends PrimeFib_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      PrimeFib.primeFib(460);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = PrimeFib.primeFib(1);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = PrimeFib.primeFib((-34));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PrimeFib primeFib0 = new PrimeFib();
  }
}
