/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:32:16 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RemoveVowels;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RemoveVowels_ESTest extends RemoveVowels_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        RemoveVowels.removeVowels((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.RemoveVowels", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("x.U8Au+s9,>ny*R<");
      assertEquals("x.8+s9,>ny*R<", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("kM/]Iu");
      assertEquals("kM/]", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels("original.RemoveVowels");
      assertEquals("rgnl.RmvVwls", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = RemoveVowels.removeVowels(";KDjzOE!}<mPQi*");
      assertEquals(";KDjz!}<mPQ*", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RemoveVowels removeVowels0 = new RemoveVowels();
  }
}
