/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:33:53 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RemoveDuplicates;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RemoveDuplicates_ESTest extends RemoveDuplicates_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Object> list0 = linkedList0.subList(0, 0);
      linkedList0.add((Object) linkedList0);
      // Undeclared exception!
      try { 
        RemoveDuplicates.removeDuplicates(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      List<Object> list0 = RemoveDuplicates.removeDuplicates(linkedList0);
      linkedList0.offerFirst(list0);
      // Undeclared exception!
      try { 
        RemoveDuplicates.removeDuplicates(linkedList0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        RemoveDuplicates.removeDuplicates((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.RemoveDuplicates", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) removeDuplicates0);
      linkedList0.add((Object) removeDuplicates0);
      List<Object> list0 = RemoveDuplicates.removeDuplicates(linkedList0);
      assertTrue(list0.isEmpty());
  }
}
