/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 23:01:58 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RightAngleTriangle;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RightAngleTriangle_ESTest extends RightAngleTriangle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle((-1), 0, 1129);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle((-3265), 1356, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(1051, 0, (-3728));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(1, (-1), 0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(0, 1, (-1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle((-1011), (-1), 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(2452, 1285, (-1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(0, (-1), 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(2637, 4177, (-1538));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle((-1), 1, (-1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle((-1), 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Boolean boolean0 = RightAngleTriangle.rightAngleTriangle(0, 0, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RightAngleTriangle rightAngleTriangle0 = new RightAngleTriangle();
  }
}
