/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:41:21 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.RoundedAvg;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RoundedAvg_ESTest extends RoundedAvg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = RoundedAvg.roundedAvg((-208), 0);
      assertEquals("0b11111111111111111111111110011000", object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      RoundedAvg.roundedAvg((-5478), 7434);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = RoundedAvg.roundedAvg(0, (-2143));
      assertEquals((-1), object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object object0 = RoundedAvg.roundedAvg(265, 265);
      assertEquals("0b100001001", object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RoundedAvg roundedAvg0 = new RoundedAvg();
  }
}
