/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:04:34 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SelectWords;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SelectWords_ESTest extends SelectWords_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SelectWords.selectWords((String) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SelectWords", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("", 0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("O$USORPt'ofNUc", 101);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("a{0.!Ip1-y\"J4/pE", (-1157));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("original.SelectWords", 0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Object> list0 = SelectWords.selectWords("'eA?u080kq<,z7i", 69);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SelectWords selectWords0 = new SelectWords();
  }
}
