/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:55:21 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SpecialFactorial;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpecialFactorial_ESTest extends SpecialFactorial_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = SpecialFactorial.specialFactorial(12);
      assertEquals((-3674937295934324736L), long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      SpecialFactorial.specialFactorial(4546);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = SpecialFactorial.specialFactorial(132);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long long0 = SpecialFactorial.specialFactorial(0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SpecialFactorial specialFactorial0 = new SpecialFactorial();
  }
}
