/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:02:57 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SplitWords;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SplitWords_ESTest extends SplitWords_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SplitWords.splitWords((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SplitWords", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = SplitWords.splitWords("X\")coL*z5yabs)O%");
      assertEquals(2, object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = SplitWords.splitWords("+VUjI 0Q$w(");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object object0 = SplitWords.splitWords("tkF13',VQMRlc>Rc");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SplitWords splitWords0 = new SplitWords();
  }
}
