/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:01:08 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.StartsOneEnds;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StartsOneEnds_ESTest extends StartsOneEnds_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = StartsOneEnds.startsOneEnds(11);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      StartsOneEnds.startsOneEnds(28);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = StartsOneEnds.startsOneEnds(1578);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = StartsOneEnds.startsOneEnds(0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StartsOneEnds startsOneEnds0 = new StartsOneEnds();
  }
}
