/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:46:31 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Strlen;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Strlen_ESTest extends Strlen_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Strlen.strlen("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Strlen.strlen((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Strlen", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Strlen strlen0 = new Strlen();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = Strlen.strlen("F)-Wr|3");
      assertEquals(8, int0);
  }
}
