/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:43:02 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.SumProduct;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SumProduct_ESTest extends SumProduct_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer((-2809));
      List<Object> list0 = linkedList0.subList(0, 0);
      linkedList0.addLast(integer0);
      // Undeclared exception!
      try { 
        SumProduct.sumProduct(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        SumProduct.sumProduct((List<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.SumProduct", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      List<Integer> list0 = SumProduct.sumProduct(linkedList0);
      linkedList0.addAll((Collection<?>) list0);
      List<Integer> list1 = SumProduct.sumProduct(linkedList0);
      assertFalse(list1.equals((Object)list0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SumProduct sumProduct0 = new SumProduct();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) sumProduct0);
      // Undeclared exception!
      try { 
        SumProduct.sumProduct(linkedList0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid number type
         //
         verifyException("original.SumProduct", e);
      }
  }
}
