/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 21:52:40 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Tri;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Tri_ESTest extends Tri_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      List<Number> list0 = Tri.tri((-1141));
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Number> list0 = Tri.tri(0);
      assertEquals(1, list0.size());
      assertFalse(list0.contains(0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tri.tri(5183);
      // Undeclared exception!
      Tri.tri(5183);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tri tri0 = new Tri();
  }
}
