/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 19:08:50 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.TriangleArea1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TriangleArea1_ESTest extends TriangleArea1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(223, 61, 223);
      assertEquals(6737.58, number0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(422, 2324, 2324);
      assertEquals(488338.75, number0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(2, 1, 1);
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(816, 816, 0);
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea((-1), (-1), 0);
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(1, 0, 0);
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(0, 0, (-1));
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(414, 414, 1);
      assertEquals(207.0, number0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Number number0 = TriangleArea1.triangleArea(414, 0, 414);
      assertEquals((-1), number0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TriangleArea1 triangleArea1_0 = new TriangleArea1();
  }
}
