/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 22:22:34 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.TriangleArea;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TriangleArea_ESTest extends TriangleArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Double double0 = TriangleArea.triangleArea((-2863), 0);
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Double double0 = TriangleArea.triangleArea(2423, (-1541));
      assertEquals((-1866921.5), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TriangleArea triangleArea0 = new TriangleArea();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Double double0 = TriangleArea.triangleArea((-40), (-40));
      assertEquals(800.0, (double)double0, 0.01);
  }
}
