/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 26 20:35:56 GMT 2023
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.WordsInSentence;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WordsInSentence_ESTest extends WordsInSentence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        WordsInSentence.wordsInSentence((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.WordsInSentence", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = WordsInSentence.wordsInSentence("original.WordsInSentence");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = WordsInSentence.wordsInSentence("T5-L0;d&e?8");
      assertEquals("T5-L0;d&e?8", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = WordsInSentence.wordsInSentence("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WordsInSentence wordsInSentence0 = new WordsInSentence();
  }
}
