// SimpleCache_1Test.java
package net.sourceforge.jwbf.core.bots.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.zip.CRC32;
import java.util.zip.Checksum;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link SimpleCache}.
* It contains ten unit test cases for the {@link SimpleCache#get(String)} method.
*/
class SimpleCache_1Test {

		private static final String TEST_FOLDER = "test_cache";
		private static final String TEST_FILE = "test_file";
		private static final String TEST_FILE_EXT = ".txt";
		private static final String TEST_FILE_CONTENT = "test_file_content";
		private static final String TEST_FILE_CONTENT_2 = "test_file_content_2";
		private static final String TEST_FILE_CONTENT_3 = "test_file_content_3";
		private static final String TEST_FILE_CONTENT_4 = "test_file_content_4";
		private static final String TEST_FILE_CONTENT_5 = "test_file_content_5";
		private static final String TEST_FILE_CONTENT_6 = "test_file_content_6";
		private static final String TEST_FILE_CONTENT_7 = "test_file_content_7";
		private static final String TEST_FILE_CONTENT_8 = "test_file_content_8";
		private static final String TEST_FILE_CONTENT_9 = "test_file_content_9";
		private static final String TEST_FILE_CONTENT_10 = "test_file_content_10";
		private static final String TEST_FILE_CONTENT_11 = "test_file_content_11";
		private static final String TEST_FILE_CONTENT_12 = "test_file_content_12";
		private static final String TEST_FILE_CONTENT_13 = "test_file_content_13";
		private static final String TEST_FILE_CONTENT_14 = "test_file_content_14";
		private static final String TEST_FILE_CONTENT_15 = "test_file_content_15";
		private static final String TEST_FILE_CONTENT_16 = "test_file_content_16";
		private static final String TEST_FILE_CONTENT_17 = "test_file_content_17";
		private static final String TEST_FILE_CONTENT_18 = "test_file_content_18";
		private static final String TEST_FILE_CONTENT_19 = "test_file_content_19";
		private static final String TEST_FILE_CONTENT_20 = "test_file_content_20";
		private static final String TEST_FILE_CONTENT_21 = "test_file_content_21";
		private static final String TEST_FILE_CONTENT_22 = "test_file_content_22";
		private static final String TEST_FILE_CONTENT_23 = "test_file_content_23";
		private static final String TEST_FILE_CONTENT_24 = "test_file_content_24";
		private static final String TEST_FILE_CONTENT_25 = "test_file_content_25";
		private static final String TEST_FILE_CONTENT_26 = "test_file_content_26";
		private static final String TEST_FILE_CONTENT_27 = "test_file_content_27";
		private static final String TEST_FILE_CONTENT_28 = "test_file_content_28";
		private static final String TEST_FILE_CONTENT_29 = "test_file_content_29";
		private static final String TEST_FILE_CONTENT_30 = "test_file_content_30";
		private static final String TEST_FILE_CONTENT_31 = "test_file_content_31";
		private static final String TEST_FILE_CONTENT_32 = "test_file_content_32";
		private static final String TEST_FILE_CONTENT_33 = "test_file_content_33";
		private static final String TEST_FILE_CONTENT_34 = "test_file_content_34";
		private static final String TEST_FILE_CONTENT_35 = "test_file_content_35";
		private static final String TEST_FILE_CONTENT_36 = "test_file_content_36";
		private static final String TEST_FILE_CONTENT_37 = "test_file_content_37";
		private static final String TEST_FILE_CONTENT_38 = "test_file_content_38";
		private static final String TEST_FILE_CONTENT_39 = "test_file_content_39";
		private static final String TEST_FILE_CONTENT_40 = "test_file_content_40";
		private static final String TEST_FILE_CONTENT_41 = "test_file_content_41";
		private static final String TEST_FILE_CONTENT_42 = "test_file_content_42";
		private static final String TEST_FILE_CONTENT_43 = "test_file_content_43";
		private static final String TEST_FILE_CONTENT_44 = "test_file_content_44";
		private static final String TEST_FILE_CONTENT_45 = "test_file_content_45";
		private static final String TEST_FILE_CONTENT_46 = "test_file_content_46";
		private static final String TEST_FILE_CONTENT_47 = "test_file_content_47";
		private static final String TEST_FILE_CONTENT_48 = "test_file_content_48";
		private static final String TEST_FILE_CONTENT_49 = "test_file_content_49";
		private static final String TEST_FILE_CONTENT_50 = "test_file_content_50";
		private static final String TEST_FILE_CONTENT_51 = "test_file_content_51";
		private static final String TEST_FILE_CONTENT_52 = "test_file_content_52";
		private static final String TEST_FILE_CONTENT_53 = "test_file_content_53";
		private static final String TEST_FILE_CONTENT_54 = "test_file_content_54";
		private static final String TEST_FILE_CONTENT_55 = "test_file_content_55";
		private static final String TEST_FILE_CONTENT_56 = "test_file_content_56";
		private static final String TEST_FILE_CONTENT_57 = "test_file_content_57";
		private static final String TEST_FILE_CONTENT_58 = "test_file_content_58";
		private static final String TEST_FILE_CONTENT_59 = "test_file_content_59";
		private static final String TEST_FILE_CONTENT_60 = "test_file_content_60";
		private static final String TEST_FILE_CONTENT_61 = "test_file_content_61";
		private static final String TEST_FILE_CONTENT_62 = "test_file_content_62";
		private static final String TEST_FILE_CONTENT_63 = "test_file_content_63";
		private static final String TEST_FILE_CONTENT_64 = "test_file_content_64";
		private static final String TEST_FILE_CONTENT_65 = "test_file_content_65";
		private static final String TEST_FILE_CONTENT_66 = "test_file_content_66";
		private static final String TEST_FILE_CONTENT_67 = "test_file_content_67";
		private static final String TEST_FILE_CONTENT_68 = "test_file_content_68";
		private static final String TEST_FILE_CONTENT_69 = "test_file_content_69";
		private static final String TEST_FILE_CONTENT_70 = "test_file_content_70";
		private static final String TEST_FILE_CONTENT_71 = "test_file_content_71";
		private static final String TEST_FILE_CONTENT_72 = "test_file_content_72";
		private static final String TEST_FILE_CONTENT_73 = "test_file_content_73";
		private static final String TEST_FILE_CONTENT_74 = "test_file_content_74";
		private static final String TEST_FILE_CONTENT_75 = "test_file_content_75";
		private static final String TEST_FILE_CONTENT_76 = "test_file_content_76";
		private static final String TEST_FILE_CONTENT_77 = "test_file_content_77";
		private static final String TEST_FILE_CONTENT_78 = "test_file_content_78";
		private static final String TEST_FILE_CONTENT_79 = "test_file_content_79";
		private static final String TEST_FILE_CONTENT_80 = "test_file_content_80";
		private static final String TEST_FILE_CONTENT_81 = "test_file_content_81";
		private static final String TEST_FILE_CONTENT_82 = "test_file_content_82";
		private static final String TEST_FILE_CONTENT_83 = "test_file_content_83";
		private static final String TEST_FILE_CONTENT_84 = "test_file_content_84";
		private static final String TEST_FILE_CONTENT_85 = "test_file_content_85";
		private static final String TEST_FILE_CONTENT_86 = "test_file_content_86";
		private static final String TEST_FILE_CONTENT_87 = "test_file_content_87";
		private static final String TEST_FILE_CONTENT_88 = "test_file_content_88";
		private static final String TEST_FILE_CONTENT_89 = "test_file_content_89";
		private static final String TEST_FILE_CONTENT_90 = "test_file_content_90";
		private static final String TEST_FILE_CONTENT_91 = "test_file_content_91";
		private static final String TEST_FILE_CONTENT_92 = "test_file_content_92";
		private static final String TEST_FILE_CONTENT_93 = "test_file_content_93";
		private static final String TEST_FILE_CONTENT_94 = "test_file_content_94";
		private static final String TEST_FILE_CONTENT_95 = "test_file_content_95";
		private static final String TEST_FILE_CONTENT_96 = "test_file_content_96";
		private static final String TEST_FILE_CONTENT_97 = "test_file_content_97";
		private static final String TEST_FILE_CONTENT_98 = "test_file_content_98";
		private static final String TEST_FILE_CONTENT_99 = "test_file_content_99";
		private static final String TEST_FILE_CONTENT_100 = "test_file_content_100";
		private static final String TEST_FILE_CONTENT_101 = "test_file_content_101";
		private static final String TEST_FILE_CONTENT_102 = "test_file_content_102";
		private static final String TEST_FILE_CONTENT_103 = "test_file_content_103";
		private static final String TEST_FILE_CONTENT_104 = "test_file_content_104";
		private static final String TEST_FILE_CONTENT_105 = "test_file_content_105";
		private static final String TEST_FILE_CONTENT_106 = "test_file_content_106";
		private static final String TEST_FILE_CONTENT_107 = "test_file_content_107";
		private static final String TEST_FILE_CONTENT_108 = "test_file_content_108";
		private static final String TEST_FILE_CONTENT_109 = "test_file_content_109";
		private static final String TEST_FILE_CONTENT_110 = "test_file_content_110";
		private static final String TEST_FILE_CONTENT_111 = "test_file_content_111";
		private static final String TEST_FILE_CONTENT_112 = "test_file_content_112";
		private static final String TEST_FILE_CONTENT_113 = "test_file_content_113";
		private static final String TEST_FILE_CONTENT_114 = "test_file_content_114";
		private static final String TEST_FILE_CONTENT_115 = "test_file_content_115";
		private static final String TEST_FILE_CONTENT_116 = "test_file_content_116";
		private static final String TEST_FILE_CONTENT_117 = "test_file_content_117";
		private static final String TEST_FILE_CONTENT_118 = "test_file_content_118";
		private static final String TEST_FILE_CONTENT_119 = "test_file_content_119";
		private static final String TEST_FILE_CONTENT_120 = "test_file_content_120";
		private static final String TEST_FILE_CONTENT_121 = "test_file_content_121";
		private static final String TEST_FILE_CONTENT_122 = "test_file_content_122";
		private static final String TEST_FILE_CONTENT_123 = "test_file_content_123";
		private static final String TEST_FILE_CONTENT_124 = "test_file_content_124";
		private static final String TEST_FILE_CONTENT_125 = "test_file_content_125";
		private static final String TEST_FILE_CONTENT_126 = "test_file_content_126";
		private static final String TEST_FILE_CONTENT_127 = "test_file_content_127";
		private static final String TEST_FILE_CONTENT_128 = "test_file_content_128";
		private static final String TEST_FILE_CONTENT_129 = "test_file_content_129";
		private static final String TEST_FILE_CONTENT_130 = "test_file_content_130";
		private static final String TEST_FILE_CONTENT_131 = "test_file_content_131";
		private static final String TEST_FILE_CONTENT_132 = "test_file_content_132";
		private static final String TEST_FILE_CONTENT_133 = "test_file_content_133";
		private static final String TEST_FILE_CONTENT_134 = "test_file_content_134";
		private static final String TEST_FILE_CONTENT_135 = "test_file_content_135";
		private static final String TEST_FILE_CONTENT_136 = "test_file_content_136";
		private static final String TEST_FILE_CONTENT_137 = "test_file_content_137";
		private static final String TEST_FILE_CONTENT_138 = "test_file_content_138";
		private static final String TEST_FILE_CONTENT_139 = "test_file_content_139";
		private static final String TEST_FILE_CONTENT_140 = "test_file_content_140";
		private static final String TEST_FILE_CONTENT_141 = "test_file_content_141";
		private static final String TEST_FILE_CONTENT_142 = "test_file_content_142";
		private static final String TEST_FILE_CONTENT_143 = "test_file_content_143";
		private static final String TEST_FILE_CONTENT_144 = "test_file_content_144";
		private static final String TEST_FILE_CONTENT_145 = "test_file_content_145";
		private static final String TEST_FILE_CONTENT_146 = "test_file_content_146";
		private static final String TEST_FILE_CONTENT_147 = "test_file_content_147";
		private static final String TEST_FILE_CONTENT_148 = "test_file_content_148";
		private static final String TEST_FILE_CONTENT_149 = "test_file_content_149";
		private static final String TEST_FILE_CONTENT_150 = "test_file_content_150";
		private static final String TEST_FILE_CONTENT_151 = "test_file_content_151";
		private static final String TEST_FILE_CONTENT_152 = "test_file_content_152";
		private static final String TEST_FILE_CONTENT_153 = "test_file_content_153";
		private static final String TEST_FILE_CONTENT_154 = "test_file_content_154";
		private static final String TEST_FILE_CONTENT_155 = "test_file_content_155";
		private static final String TEST_FILE_CONTENT_156 = "test_file_content_156";
		private static final String TEST_FILE_CONTENT_157 = "test_file_content_157";
		private static final String TEST_FILE_CONTENT_158 = "test_file_content_158";
		private