// IscubeTest.java
package scenario2;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Iscube}.
* It contains ten unit test cases for the {@link Iscube#iscube(int)} method.
*/
class IscubeTest {

    /**
     * Test case for {@link Iscube#iscube(int)}.
     */
    @Test
    void testIscube() {
        assertTrue(Iscube.iscube(1));
        assertTrue(Iscube.iscube(8));
        assertTrue(Iscube.iscube(27));
        assertTrue(Iscube.iscube(64));
        assertTrue(Iscube.iscube(125));
        assertTrue(Iscube.iscube(216));
        assertTrue(Iscube.iscube(343));
        assertTrue(Iscube.iscube(512));
        assertTrue(Iscube.iscube(729));
        assertTrue(Iscube.iscube(1000));
        assertFalse(Iscube.iscube(0));
        assertFalse(Iscube.iscube(-1));
        assertFalse(Iscube.iscube(2));
        assertFalse(Iscube.iscube(3));
        assertFalse(Iscube.iscube(4));
        assertFalse(Iscube.iscube(5));
        assertFalse(Iscube.iscube(6));
        assertFalse(Iscube.iscube(7));
        assertFalse(Iscube.iscube(9));
        assertFalse(Iscube.iscube(10));
        assertFalse(Iscube.iscube(11));
        assertFalse(Iscube.iscube(12));
        assertFalse(Iscube.iscube(13));
        assertFalse(Iscube.iscube(14));
        assertFalse(Iscube.iscube(15));
        assertFalse(Iscube.iscube(16));
        assertFalse(Iscube.iscube(17));
        assertFalse(Iscube.iscube(18));
        assertFalse(Iscube.iscube(19));
        assertFalse(Iscube.iscube(20));
        assertFalse(Iscube.iscube(21));
        assertFalse(Iscube.iscube(22));
        assertFalse(Iscube.iscube(23));
        assertFalse(Iscube.iscube(24));
        assertFalse(Iscube.iscube(25));
        assertFalse(Iscube.iscube(26));
        assertFalse(Iscube.iscube(28));
        assertFalse(Iscube.iscube(29));
        assertFalse(Iscube.iscube(30));
        assertFalse(Iscube.iscube(31));
        assertFalse(Iscube.iscube(32));
        assertFalse(Iscube.iscube(33));
        assertFalse(Iscube.iscube(34));
        assertFalse(Iscube.iscube(35));
        assertFalse(Iscube.iscube(36));
        assertFalse(Iscube.iscube(37));
        assertFalse(Iscube.iscube(38));
        assertFalse(Iscube.iscube(39));
        assertFalse(Iscube.iscube(40));
        assertFalse(Iscube.iscube(41));
        assertFalse(Iscube.iscube(42));
        assertFalse(Iscube.iscube(43));
        assertFalse(Iscube.iscube(44));
        assertFalse(Iscube.iscube(45));
        assertFalse(Iscube.iscube(46));
        assertFalse(Iscube.iscube(47));
        assertFalse(Iscube.iscube(48));
        assertFalse(Iscube.iscube(49));
        assertFalse(Iscube.iscube(50));
        assertFalse(Iscube.iscube(51));
        assertFalse(Iscube.iscube(52));
        assertFalse(Iscube.iscube(53));
        assertFalse(Iscube.iscube(54));
        assertFalse(Iscube.iscube(55));
        assertFalse(Iscube.iscube(56));
        assertFalse(Iscube.iscube(57));
        assertFalse(Iscube.iscube(58));
        assertFalse(Iscube.iscube(59));
        assertFalse(Iscube.iscube(60));
        assertFalse(Iscube.iscube(61));
        assertFalse(Iscube.iscube(62));
        assertFalse(Iscube.iscube(63));
        assertFalse(Iscube.iscube(65));
        assertFalse(Iscube.iscube(66));
        assertFalse(Iscube.iscube(67));
        assertFalse(Iscube.iscube(68));
        assertFalse(Iscube.iscube(69));
        assertFalse(Iscube.iscube(70));
        assertFalse(Iscube.iscube(71));
        assertFalse(Iscube.iscube(72));
        assertFalse(Iscube.iscube(73));
        assertFalse(Iscube.iscube(74));
        assertFalse(Iscube.iscube(75));
        assertFalse(Iscube.iscube(76));
        assertFalse(Iscube.iscube(77));
        assertFalse(Iscube.iscube(78));
        assertFalse(Iscube.iscube(79));
        assertFalse(Iscube.iscube(80));
        assertFalse(Iscube.iscube(81));
        assertFalse(Iscube.iscube(82));
        assertFalse(Iscube.iscube(83));
        assertFalse(Iscube.iscube(84));
        assertFalse(Iscube.iscube(85));
        assertFalse(Iscube.iscube(86));
        assertFalse(Iscube.iscube(87));
        assertFalse(Iscube.iscube(88));
        assertFalse(Iscube.iscube(89));
        assertFalse(Iscube.iscube(90));
        assertFalse(Iscube.iscube(91));
        assertFalse(Iscube.iscube(92));
        assertFalse(Iscube.iscube(93));
        assertFalse(Iscube.iscube(94));
        assertFalse(Iscube.iscube(95));
        assertFalse(Iscube.iscube(96));
        assertFalse(Iscube.iscube(97));
        assertFalse(Iscube.iscube(98));
        assertFalse(Iscube.iscube(99));
        assertFalse(Iscube.iscube(100));
        assertFalse(Iscube.iscube(101));
        assertFalse(Iscube.iscube(102));
        assertFalse(Iscube.iscube(103));
        assertFalse(Iscube.iscube(104));
        assertFalse(Iscube.iscube(105));
        assertFalse(Iscube.iscube(106));
        assertFalse(Iscube.iscube(107));
        assertFalse(Iscube.iscube(108));
        assertFalse(Iscube.iscube(109));
        assertFalse(Iscube.iscube(110));
        assertFalse(Iscube.iscube(111));
        assertFalse(Iscube.iscube(112));
        assertFalse(Iscube.iscube(113));
        assertFalse(Iscube.iscube(114));
        assertFalse(Iscube.iscube(115));
        assertFalse(Iscube.iscube(116));
        assertFalse(Iscube.iscube(117));
        assertFalse(Iscube.iscube(118));
        assertFalse(Iscube.iscube(119));
        assertFalse(Iscube.iscube(120));
        assertFalse(Iscube.iscube(121));
        assertFalse(Iscube.iscube(122));
        assertFalse(Iscube.iscube(123));
        assertFalse(Iscube.iscube(124));
        assertFalse(Iscube.iscube(126));
        assertFalse(Iscube.iscube(127));
        assertFalse(Iscube.iscube(128));
        assertFalse(Iscube.iscube(129));
        assertFalse(Iscube.iscube(130));
        assertFalse(Iscube.iscube(131));
        assertFalse(Iscube.iscube(132));
        assertFalse(Iscube.iscube(133));
        assertFalse(Iscube.iscube(134));
        assertFalse(Iscube.iscube(135));
        assertFalse(Iscube.iscube(136));
        assertFalse(Iscube.iscube(137));
        assertFalse(Iscube.iscube(138));
        assertFalse(Iscube.iscube(139));
        assertFalse(Iscube.iscube(140));
        assertFalse(Iscube.iscube(141));
        assertFalse(Iscube.iscube