// ModernChatServer_7Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#sendSecureBinaryMessage(BinaryMessage)} method.
*/
class ModernChatServer_7Test {

    /**
     * Test case for the {@link ModernChatServer#sendSecureBinaryMessage(BinaryMessage)} method.
     * It tests the method with a valid message.
     * @throws RemoteException
     */
    @Test
    void testSendSecureBinaryMessage_1() throws RemoteException {
        ModernChatServer server = new ModernChatServer();
        BinaryMessage msg = new BinaryMessage();
        msg.setSender("sender");
        msg.setReceiver("receiver");
        msg.setFileName("fileName");
        msg.setFileData("fileData");
        msg.setFileExtension("fileExtension");
        msg.setFileSize(100);
        msg.setFileId(1);
        msg.setFileDate(Calendar.getInstance().getTime());
        msg.setFileTime(Calendar.getInstance().getTime());
        msg.setFileSender("fileSender");
        msg.setFileReceiver("fileReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
        msg.setFileStatusDate(Calendar.getInstance().getTime());
        msg.setFileStatusTime(Calendar.getInstance().getTime());
        msg.setFileStatusSender("fileStatusSender");
        msg.setFileStatusReceiver("fileStatusReceiver");
        msg.setFileStatus(IConstant.FILE_STATUS_RECEIVED);
       