// DownloadFolderTag_1Test.java
package org.heal.tag.download;

import org.heal.module.download.DownloadQueueBean;
import org.heal.module.metadata.ShortMetadataBean;
import org.heal.util.FileLocator;
import javax.servlet.jsp.tagext.TagSupport;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link DownloadFolderTag}.
* It contains ten unit test cases for the {@link DownloadFolderTag#doEndTag()} method.
*/
class DownloadFolderTag_1Test {

    /**
    * Test method for {@link DownloadFolderTag#doEndTag()}.
    */
    @Test
    void testDoEndTag() {
        DownloadFolderTag tag = new DownloadFolderTag();
        DownloadQueueBean downloadQueue = new DownloadQueueBean();
        ShortMetadataBean shortMetadata = new ShortMetadataBean();
        FileLocator locator = new FileLocator();
        locator.setServerBaseURL("http://localhost:8080/heal/images/");
        tag.setDownloadQueue(downloadQueue);
        tag.setShortMetadata(shortMetadata);
        tag.setPageContext(new MockPageContext(locator));
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        tag.doEndTag();
        assertEquals(DownloadFolderTag.UNAVAILABLE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.ADD, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.html");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Image");
        shortMetadata.setLocation("http://localhost:8080/heal/images/test.jpg");
        downloadQueue.add(shortMetadata.getMetadataId());
        tag.doEndTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        tag.doStartTag();
        assertEquals(DownloadFolderTag.REMOVE, tag.getDownloadFolderType());
        shortMetadata.setFormat("Web Page");
        shortMetadata.