// WorkerMgr_0Test.java
package com.hf.sfm.system.business;

import org.hibernate.Transaction;
import com.hf.sfm.sfmis.personinfo.business.PersonInfoMgr;
import com.hf.sfm.system.pdo.AWorker;
import com.hf.sfm.util.DaoFactory;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link WorkerMgr}.
* It contains ten unit test cases for the {@link WorkerMgr#saveOrUpdate(AWorker)} method.
*/
class WorkerMgr_0Test {

	/**
	* Test case 1:
	* 		idno: null
	* 		password: null
	* 		name: null
	* 		sex: null
	* 		birthday: null
	* 		idtype: null
	* 		idno: null
	* 		address: null
	* 		postcode: null
	* 		tel: null
	* 		mobile: null
	* 		email: null
	* 		qq: null
	* 		msn: null
	* 		remark: null
	* 		status: null
	* 		createdate: null
	* 		updatedate: null
	* 		createuser: null
	* 		updateuser: null
	* 		deptid: null
	* 		deptname: null
	* 		roleid: null
	* 		rolename: null
	* 		roledesc: null
	* 		roletype: null
	* 		rolelevel: null
	* 		rolesort: null
	* 		roleremark: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	* 		roleqq: null
	* 		rolemsn: null
	* 		roleremark: null
	* 		rolestatus: null
	* 		rolecreatedate: null
	* 		roleupdatedate: null
	* 		rolecreateuser: null
	* 		roleupdateuser: null
	* 		roleidno: null
	* 		roleidtype: null
	* 		roleidtypename: null
	* 		rolesex: null
	* 		rolesexname: null
	* 		rolebirthday: null
	* 		roleaddress: null
	* 		rolepostcode: null
	* 		roletel: null
	* 		rolemobile: null
	* 		roleemail: null
	*