// Login_3Test.java
package com.browsersoft.aacs;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.TimeZone;
import javax.security.auth.login.LoginException;
import org.apache.log4j.FileAppender;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.SimpleLayout;
import com.browsersoft.aacs.xacml.PDPadapter;
import com.browsersoft.aacs.xacml.RequestBuilder;
import com.sun.xacml.Indenter;
import com.sun.xacml.ctx.RequestCtx;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Login}.
* It contains ten unit test cases for the {@link Login#authorize()} method.
*/
class Login_3Test {

    private static final Logger cat = Logger.getLogger(Login_3Test.class);
    private static final String TEST_CONFIG_FILE = "test.properties";
    private static final String TEST_CONFIG_FILE_2 = "test2.properties";
    private static final String TEST_CONFIG_FILE_3 = "test3.properties";
    private static final String TEST_CONFIG_FILE_4 = "test4.properties";
    private static final String TEST_CONFIG_FILE_5 = "test5.properties";
    private static final String TEST_CONFIG_FILE_6 = "test6.properties";
    private static final String TEST_CONFIG_FILE_7 = "test7.properties";
    private static final String TEST_CONFIG_FILE_8 = "test8.properties";
    private static final String TEST_CONFIG_FILE_9 = "test9.properties";
    private static final String TEST_CONFIG_FILE_10 = "test10.properties";
    private static final String TEST_CONFIG_FILE_11 = "test11.properties";
    private static final String TEST_CONFIG_FILE_12 = "test12.properties";
    private static final String TEST_CONFIG_FILE_13 = "test13.properties";
    private static final String TEST_CONFIG_FILE_14 = "test14.properties";
    private static final String TEST_CONFIG_FILE_15 = "test15.properties";
    private static final String TEST_CONFIG_FILE_16 = "test16.properties";
    private static final String TEST_CONFIG_FILE_17 = "test17.properties";
    private static final String TEST_CONFIG_FILE_18 = "test18.properties";
    private static final String TEST_CONFIG_FILE_19 = "test19.properties";
    private static final String TEST_CONFIG_FILE_20 = "test20.properties";
    private static final String TEST_CONFIG_FILE_21 = "test21.properties";
    private static final String TEST_CONFIG_FILE_22 = "test22.properties";
    private static final String TEST_CONFIG_FILE_23 = "test23.properties";
    private static final String TEST_CONFIG_FILE_24 = "test24.properties";
    private static final String TEST_CONFIG_FILE_25 = "test25.properties";
    private static final String TEST_CONFIG_FILE_26 = "test26.properties";
    private static final String TEST_CONFIG_FILE_27 = "test27.properties";
    private static final String TEST_CONFIG_FILE_28 = "test28.properties";
    private static final String TEST_CONFIG_FILE_29 = "test29.properties";
    private static final String TEST_CONFIG_FILE_30 = "test30.properties";
    private static final String TEST_CONFIG_FILE_31 = "test31.properties";
    private static final String TEST_CONFIG_FILE_32 = "test32.properties";
    private static final String TEST_CONFIG_FILE_33 = "test33.properties";
    private static final String TEST_CONFIG_FILE_34 = "test34.properties";
    private static final String TEST_CONFIG_FILE_35 = "test35.properties";
    private static final String TEST_CONFIG_FILE_36 = "test36.properties";
    private static final String TEST_CONFIG_FILE_37 = "test37.properties";
    private static final String TEST_CONFIG_FILE_38 = "test38.properties";
    private static final String TEST_CONFIG_FILE_39 = "test39.properties";
    private static final String TEST_CONFIG_FILE_40 = "test40.properties";
    private static final String TEST_CONFIG_FILE_41 = "test41.properties";
    private static final String TEST_CONFIG_FILE_42 = "test42.properties";
    private static final String TEST_CONFIG_FILE_43 = "test43.properties";
    private static final String TEST_CONFIG_FILE_44 = "test44.properties";
    private static final String TEST_CONFIG_FILE_45 = "test45.properties";
    private static final String TEST_CONFIG_FILE_46 = "test46.properties";
    private static final String TEST_CONFIG_FILE_47 = "test47.properties";
    private static final String TEST_CONFIG_FILE_48 = "test48.properties";
    private static final String TEST_CONFIG_FILE_49 = "test49.properties";
    private static final String TEST_CONFIG_FILE_50 = "test50.properties";
    private static final String TEST_CONFIG_FILE_51 = "test51.properties";
    private static final String TEST_CONFIG_FILE_52 = "test52.properties";
    private static final String TEST_CONFIG_FILE_53 = "test53.properties";
    private static final String TEST_CONFIG_FILE_54 = "test54.properties";
    private static final String TEST_CONFIG_FILE_55 = "test55.properties";
    private static final String TEST_CONFIG_FILE_56 = "test56.properties";
    private static final String TEST_CONFIG_FILE_57 = "test57.properties";
    private static final String TEST_CONFIG_FILE_58 = "test58.properties";
    private static final String TEST_CONFIG_FILE_59 = "test59.properties";
    private static final String TEST_CONFIG_FILE_60 = "test60.properties";
    private static final String TEST_CONFIG_FILE_61 = "test61.properties";
    private static final String TEST_CONFIG_FILE_62 = "test62.properties";
    private static final String TEST_CONFIG_FILE_63 = "test63.properties";
    private static final String TEST_CONFIG_FILE_64 = "test64.properties";
    private static final String TEST_CONFIG_FILE_65 = "test65.properties";
    private static final String TEST_CONFIG_FILE_66 = "test66.properties";
    private static final String TEST_CONFIG_FILE_67 = "test67.properties";
    private static final String TEST_CONFIG_FILE_68 = "test68.properties";
    private static final String TEST_CONFIG_FILE_69 = "test69.properties";
    private static final String TEST_CONFIG_FILE_70 = "test70.properties";
    private static final String TEST_CONFIG_FILE_71 = "test71.properties";
    private static final String TEST_CONFIG_FILE_72 = "test72.properties";
    private static final String TEST_CONFIG_FILE_73 = "test73.properties";
    private static final String TEST_CONFIG_FILE_74 = "test74.properties";
    private static final String TEST_CONFIG_FILE_75 = "test75.properties";
    private static final String TEST_CONFIG_FILE_76 = "test76.properties";
    private static final String TEST_CONFIG_FILE_77 = "test77.properties";
    private static final String TEST_CONFIG_FILE_78 = "test78.properties";
    private static final String TEST_CONFIG_FILE_79 = "test79.properties";
    private static final String TEST_CONFIG_FILE_80 = "test80.properties";
    private static final String TEST_CONFIG_FILE_81 = "test81.properties";
    private static final String TEST_CONFIG_FILE_82 = "test82.properties";
    private static final String TEST_CONFIG_FILE_83 = "test83.properties";
    private static final String TEST_CONFIG_FILE_84 = "test84.properties";
    private static final String TEST_CONFIG_FILE_85 = "test85.properties";
    private static final String TEST_CONFIG_FILE_86 = "test86.properties";
    private static final String TEST_CONFIG_FILE_87 = "test87.properties";
    private static final String TEST_CONFIG_FILE_88 = "test88.properties";
    private static final String TEST_CONFIG_FILE_89 = "test89.properties";
    private static final String TEST_CONFIG_FILE_90 = "test90.properties";
    private static final String TEST_CONFIG_FILE_91 = "test91.properties";
    private static final String TEST_CONFIG_FILE_92 = "test92.properties";
    private static final String TEST_CONFIG_FILE_93 = "test93.properties";
    private static final String TEST_CONFIG_FILE_94 = "test94.properties";
    private static final String TEST_CONFIG_FILE_95 = "test95.properties";
    private static final String TEST_CONFIG