// SimpleUserMgr_1Test.java
package com.browsersoft.aacs;

import jdbm.JDBMEnumeration;
import jdbm.JDBMHashtable;
import jdbm.JDBMRecordManager;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Properties;
import java.util.StringTokenizer;
import java.util.Vector;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link SimpleUserMgr}.
* It contains ten unit test cases for the {@link SimpleUserMgr#getNamesbyOrg(String)} method.
*/
class SimpleUserMgr_1Test {

    private static final String TEST_DATA_FILE = "test_data.txt";
    private static final String TEST_DATA_FILE_2 = "test_data_2.txt";
    private static final String TEST_DATA_FILE_3 = "test_data_3.txt";
    private static final String TEST_DATA_FILE_4 = "test_data_4.txt";
    private static final String TEST_DATA_FILE_5 = "test_data_5.txt";
    private static final String TEST_DATA_FILE_6 = "test_data_6.txt";
    private static final String TEST_DATA_FILE_7 = "test_data_7.txt";
    private static final String TEST_DATA_FILE_8 = "test_data_8.txt";
    private static final String TEST_DATA_FILE_9 = "test_data_9.txt";
    private static final String TEST_DATA_FILE_10 = "test_data_10.txt";
    private static final String TEST_DATA_FILE_11 = "test_data_11.txt";
    private static final String TEST_DATA_FILE_12 = "test_data_12.txt";
    private static final String TEST_DATA_FILE_13 = "test_data_13.txt";
    private static final String TEST_DATA_FILE_14 = "test_data_14.txt";
    private static final String TEST_DATA_FILE_15 = "test_data_15.txt";
    private static final String TEST_DATA_FILE_16 = "test_data_16.txt";
    private static final String TEST_DATA_FILE_17 = "test_data_17.txt";
    private static final String TEST_DATA_FILE_18 = "test_data_18.txt";
    private static final String TEST_DATA_FILE_19 = "test_data_19.txt";
    private static final String TEST_DATA_FILE_20 = "test_data_20.txt";
    private static final String TEST_DATA_FILE_21 = "test_data_21.txt";
    private static final String TEST_DATA_FILE_22 = "test_data_22.txt";
    private static final String TEST_DATA_FILE_23 = "test_data_23.txt";
    private static final String TEST_DATA_FILE_24 = "test_data_24.txt";
    private static final String TEST_DATA_FILE_25 = "test_data_25.txt";
    private static final String TEST_DATA_FILE_26 = "test_data_26.txt";
    private static final String TEST_DATA_FILE_27 = "test_data_27.txt";
    private static final String TEST_DATA_FILE_28 = "test_data_28.txt";
    private static final String TEST_DATA_FILE_29 = "test_data_29.txt";
    private static final String TEST_DATA_FILE_30 = "test_data_30.txt";
    private static final String TEST_DATA_FILE_31 = "test_data_31.txt";
    private static final String TEST_DATA_FILE_32 = "test_data_32.txt";
    private static final String TEST_DATA_FILE_33 = "test_data_33.txt";
    private static final String TEST_DATA_FILE_34 = "test_data_34.txt";
    private static final String TEST_DATA_FILE_35 = "test_data_35.txt";
    private static final String TEST_DATA_FILE_36 = "test_data_36.txt";
    private static final String TEST_DATA_FILE_37 = "test_data_37.txt";
    private static final String TEST_DATA_FILE_38 = "test_data_38.txt";
    private static final String TEST_DATA_FILE_39 = "test_data_39.txt";
    private static final String TEST_DATA_FILE_40 = "test_data_40.txt";
    private static final String TEST_DATA_FILE_41 = "test_data_41.txt";
    private static final String TEST_DATA_FILE_42 = "test_data_42.txt";
    private static final String TEST_DATA_FILE_43 = "test_data_43.txt";
    private static final String TEST_DATA_FILE_44 = "test_data_44.txt";
    private static final String TEST_DATA_FILE_45 = "test_data_45.txt";
    private static final String TEST_DATA_FILE_46 = "test_data_46.txt";
    private static final String TEST_DATA_FILE_47 = "test_data_47.txt";
    private static final String TEST_DATA_FILE_48 = "test_data_48.txt";
    private static final String TEST_DATA_FILE_49 = "test_data_49.txt";
    private static final String TEST_DATA_FILE_50 = "test_data_50.txt";
    private static final String TEST_DATA_FILE_51 = "test_data_51.txt";
    private static final String TEST_DATA_FILE_52 = "test_data_52.txt";
    private static final String TEST_DATA_FILE_53 = "test_data_53.txt";
    private static final String TEST_DATA_FILE_54 = "test_data_54.txt";
    private static final String TEST_DATA_FILE_55 = "test_data_55.txt";
    private static final String TEST_DATA_FILE_56 = "test_data_56.txt";
    private static final String TEST_DATA_FILE_57 = "test_data_57.txt";
    private static final String TEST_DATA_FILE_58 = "test_data_58.txt";
    private static final String TEST_DATA_FILE_59 = "test_data_59.txt";
    private static final String TEST_DATA_FILE_60 = "test_data_60.txt";
    private static final String TEST_DATA_FILE_61 = "test_data_61.txt";
    private static final String TEST_DATA_FILE_62 = "test_data_62.txt";
    private static final String TEST_DATA_FILE_63 = "test_data_63.txt";
    private static final String TEST_DATA_FILE_64 = "test_data_64.txt";
    private static final String TEST_DATA_FILE_65 = "test_data_65.txt";
    private static final String TEST_DATA_FILE_66 = "test_data_66.txt";
    private static final String TEST_DATA_FILE_67 = "test_data_67.txt";
    private static final String TEST_DATA_FILE_68 = "test_data_68.txt";
    private static final String TEST_DATA_FILE_69 = "test_data_69.txt";
    private static final String TEST_DATA_FILE_70 = "test_data_70.txt";
    private static final String TEST_DATA_FILE_71 = "test_data_71.txt";
    private static final String TEST_DATA_FILE_72 = "test_data_72.txt";
    private static final String TEST_DATA_FILE_73 = "test_data_73.txt";
    private static final String TEST_DATA_FILE_74 = "test_data_74.txt";
    private static final String TEST_DATA_FILE_75 = "test_data_75.txt";
    private static final String TEST_DATA_FILE_76 = "test_data_76.txt";
    private static final String TEST_DATA_FILE_77 = "test_data_77.txt";
    private static final String TEST_DATA_FILE_78 = "test_data_78.txt";
    private static final String TEST_DATA_FILE_79 = "test_data_79.txt";
    private static final String TEST_DATA_FILE_80 = "test_data_80.txt";
    private static final String TEST_DATA_FILE_81 = "test_data_81.txt";
    private static final String TEST_DATA_FILE_82 = "test_data_82.txt";
    private static final String TEST_DATA_FILE_83 = "test_data_83.txt";
    private static final String TEST_DATA_FILE_84 = "test_data_84.txt";
    private static final String TEST