// SimpleUserMgr_2Test.java
package com.browsersoft.aacs;

import jdbm.JDBMEnumeration;
import jdbm.JDBMHashtable;
import jdbm.JDBMRecordManager;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Properties;
import java.util.StringTokenizer;
import java.util.Vector;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link SimpleUserMgr}.
* It contains ten unit test cases for the {@link SimpleUserMgr#getMailbyOrg(String)} method.
*/
class SimpleUserMgr_2Test {

    private static final String TEST_FILE = "test.txt";
    private static final String TEST_FILE_2 = "test2.txt";
    private static final String TEST_FILE_3 = "test3.txt";
    private static final String TEST_FILE_4 = "test4.txt";
    private static final String TEST_FILE_5 = "test5.txt";
    private static final String TEST_FILE_6 = "test6.txt";
    private static final String TEST_FILE_7 = "test7.txt";
    private static final String TEST_FILE_8 = "test8.txt";
    private static final String TEST_FILE_9 = "test9.txt";
    private static final String TEST_FILE_10 = "test10.txt";
    private static final String TEST_FILE_11 = "test11.txt";
    private static final String TEST_FILE_12 = "test12.txt";
    private static final String TEST_FILE_13 = "test13.txt";
    private static final String TEST_FILE_14 = "test14.txt";
    private static final String TEST_FILE_15 = "test15.txt";
    private static final String TEST_FILE_16 = "test16.txt";
    private static final String TEST_FILE_17 = "test17.txt";
    private static final String TEST_FILE_18 = "test18.txt";
    private static final String TEST_FILE_19 = "test19.txt";
    private static final String TEST_FILE_20 = "test20.txt";
    private static final String TEST_FILE_21 = "test21.txt";
    private static final String TEST_FILE_22 = "test22.txt";
    private static final String TEST_FILE_23 = "test23.txt";
    private static final String TEST_FILE_24 = "test24.txt";
    private static final String TEST_FILE_25 = "test25.txt";
    private static final String TEST_FILE_26 = "test26.txt";
    private static final String TEST_FILE_27 = "test27.txt";
    private static final String TEST_FILE_28 = "test28.txt";
    private static final String TEST_FILE_29 = "test29.txt";
    private static final String TEST_FILE_30 = "test30.txt";
    private static final String TEST_FILE_31 = "test31.txt";
    private static final String TEST_FILE_32 = "test32.txt";
    private static final String TEST_FILE_33 = "test33.txt";
    private static final String TEST_FILE_34 = "test34.txt";
    private static final String TEST_FILE_35 = "test35.txt";
    private static final String TEST_FILE_36 = "test36.txt";
    private static final String TEST_FILE_37 = "test37.txt";
    private static final String TEST_FILE_38 = "test38.txt";
    private static final String TEST_FILE_39 = "test39.txt";
    private static final String TEST_FILE_40 = "test40.txt";
    private static final String TEST_FILE_41 = "test41.txt";
    private static final String TEST_FILE_42 = "test42.txt";
    private static final String TEST_FILE_43 = "test43.txt";
    private static final String TEST_FILE_44 = "test44.txt";
    private static final String TEST_FILE_45 = "test45.txt";
    private static final String TEST_FILE_46 = "test46.txt";
    private static final String TEST_FILE_47 = "test47.txt";
    private static final String TEST_FILE_48 = "test48.txt";
    private static final String TEST_FILE_49 = "test49.txt";
    private static final String TEST_FILE_50 = "test50.txt";
    private static final String TEST_FILE_51 = "test51.txt";
    private static final String TEST_FILE_52 = "test52.txt";
    private static final String TEST_FILE_53 = "test53.txt";
    private static final String TEST_FILE_54 = "test54.txt";
    private static final String TEST_FILE_55 = "test55.txt";
    private static final String TEST_FILE_56 = "test56.txt";
    private static final String TEST_FILE_57 = "test57.txt";
    private static final String TEST_FILE_58 = "test58.txt";
    private static final String TEST_FILE_59 = "test59.txt";
    private static final String TEST_FILE_60 = "test60.txt";
    private static final String TEST_FILE_61 = "test61.txt";
    private static final String TEST_FILE_62 = "test62.txt";
    private static final String TEST_FILE_63 = "test63.txt";
    private static final String TEST_FILE_64 = "test64.txt";
    private static final String TEST_FILE_65 = "test65.txt";
    private static final String TEST_FILE_66 = "test66.txt";
    private static final String TEST_FILE_67 = "test67.txt";
    private static final String TEST_FILE_68 = "test68.txt";
    private static final String TEST_FILE_69 = "test69.txt";
    private static final String TEST_FILE_70 = "test70.txt";
    private static final String TEST_FILE_71 = "test71.txt";
    private static final String TEST_FILE_72 = "test72.txt";
    private static final String TEST_FILE_73 = "test73.txt";
    private static final String TEST_FILE_74 = "test74.txt";
    private static final String TEST_FILE_75 = "test75.txt";
    private static final String TEST_FILE_76 = "test76.txt";
    private static final String TEST_FILE_77 = "test77.txt";
    private static final String TEST_FILE_78 = "test78.txt";
    private static final String TEST_FILE_79 = "test79.txt";
    private static final String TEST_FILE_80 = "test80.txt";
    private static final String TEST_FILE_81 = "test81.txt";
    private static final String TEST_FILE_82 = "test82.txt";
    private static final String TEST_FILE_83 = "test83.txt";
    private static final String TEST_FILE_84 = "test84.txt";
    private static final String TEST_FILE_85 = "test85.txt";
    private static final String TEST_FILE_86 = "test86.txt";
    private static final String TEST_FILE_87 = "test87.txt";
    private static final String TEST_FILE_88 = "test88.txt";
    private static final String TEST_FILE_89 = "test89.txt";
    private static final String TEST_FILE_90 = "test90.txt";
    private static final String TEST_FILE_91 = "test91.txt";
    private static final String TEST_FILE_92 = "test92.txt";
    private static final String TEST_FILE_93 = "test93.txt";
    private static final String TEST_FILE_94 = "test94.txt";
    private static final String TEST_FILE_95 = "test95.txt";
    private static final String TEST_FILE_96 = "test96.txt";
    private static final String TEST_FILE_97 = "test97.txt";
    private static final String TEST_FILE_98 = "test98.txt";
    private static final String TEST_FILE_99 = "test99.txt";
    private static final String TEST_FILE_100 = "test100.txt";
    private static final String TEST_FILE_101 = "test101.txt";
    private static final String TEST_FILE_102 = "test102.txt";
    private static final String TEST_FILE_103 = "test103.txt";
    private static final String TEST_FILE_104 = "test104.txt";
    private static final String TEST_FILE_105 = "test105.txt";
    private static final String TEST_FILE_106 = "