rm -rf ../../ICSE23-results/OpenAI/SF110-Results/100_jgaap/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/103_sweethome3d/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/10_water-simulator/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/11_imsmart/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/12_dsachat/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/14_omjstate/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/17_inspirento/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/19_jmca/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/22_byuic/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/23_jwbf/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/24_saxpath/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/25_jni-inchi/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/29_apbsmem/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/2_a4j/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/31_xisemele/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/32_httpanalyzer/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/33_javaviewcontrol/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/34_sbmlreader2/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/39_diffi/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/40_glengineer/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/41_follow/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/42_asphodel/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/43_lilith/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/47_dvd-homevideo/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/49_diebierse/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/4_rif/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/52_lagoon/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/56_jhandballmoves/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/57_hft-bomberman/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/59_mygrid/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/5_templateit/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/60_sugar/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/63_objectexplorer/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/64_jtailgui/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/67_gae-app-manager/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/68_biblestudy/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/69_lhamacaw/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/6_jnfe/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/71_ext4j/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/73_fim1/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/74_fixsuite/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/75_openhre/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/79_twfbplayer/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/7_sfmis/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/81_javathena/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/82_ipcalculator/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/84_ifx-framework/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/86_at-robots2-j/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/8_gfarcegestionfa/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/91_classviewer/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/93_quickserver/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/94_jclo/src/test/java/
rm -rf ../../ICSE23-results/OpenAI/SF110-Results/96_heal/src/test/java/