// CurrentPlayersTest2.java
package src;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link CurrentPlayers}.
* It contains ten unit test cases for the {@link CurrentPlayers#whosThere(String)} method.
*/
class CurrentPlayersTest2 {

		/**
		* Test case for {@link CurrentPlayers#whosThere(String)} method.
		* It tests if the method returns the correct list of players in a fief.
		*/
		@Test
		void testWhosThere() {
				ArrayList<String> expected = new ArrayList<String>();
				expected.add("John");
				expected.add("Bob");
				expected.add("Alice");
				expected.add("Eve");
				expected.add("Mallory");
				expected.add("Trent");
				expected.add("Victor");
				expected.add("Walter");
				expected.add("Carol");
				expected.add("Oscar");
				expected.add("Peggy");
				expected.add("Laura");
				expected.add("Dave");
				expected.add("Charlie");
				expected.add("Dan");
				expected.add("Ed");
				expected.add("Frank");
				expected.add("Gavin");
				expected.add("Hal");
				expected.add("Ivan");
				expected.add("Jill");
				expected.add("Kurt");
				expected.add("Larry");
				expected.add("Mike");
				expected.add("Ned");
				expected.add("Olivia");
				expected.add("Pat");
				expected.add("Quinn");
				expected.add("Rachel");
				expected.add("Sybil");
				expected.add("Trudy");
				expected.add("Ursula");
				expected.add("Vera");
				expected.add("Wendy");
				expected.add("Xavier");
				expected.add("Yvonne");
				expected.add("Zoe");
				expected.add("Abe");
				expected.add("Barry");
				expected.add("Cecil");
				expected.add("Dennis");
				expected.add("Ernie");
				expected.add("Fred");
				expected.add("George");
				expected.add("Henry");
				expected.add("Ike");
				expected.add("Jerry");
				expected.add("Karl");
				expected.add("Lloyd");
				expected.add("Moe");
				expected.add("Nate");
				expected.add("Otto");
				expected.add("Paul");
				expected.add("Quigley");
				expected.add("Ralph");
				expected.add("Sam");
				expected.add("Ted");
				expected.add("Ulysses");
				expected.add("Vince");
				expected.add("Walt");
				expected.add("Xavier");
				expected.add("Yancy");
				expected.add("Zach");
				expected.add("Abel");
				expected.add("Baker");
				expected.add("Charlie");
				expected.add("Dog");
				expected.add("Easy");
				expected.add("Fox");
				expected.add("George");
				expected.add("How");
				expected.add("Item");
				expected.add("Jig");
				expected.add("King");
				expected.add("Love");
				expected.add("Mike");
				expected.add("Nan");
				expected.add("Oboe");
				expected.add("Peter");
				expected.add("Queen");
				expected.add("Roger");
				expected.add("Sail");
				expected.add("Tare");
				expected.add("Uncle");
				expected.add("Victor");
				expected.add("William");
				expected.add("X-ray");
				expected.add("Yoke");
				expected.add("Zebra");
				expected.add("Alfred");
				expected.add("Bert");
				expected.add("Charles");
				expected.add("David");
				expected.add("Edward");
				expected.add("Fred");
				expected.add("George");
				expected.add("Harry");
				expected.add("Ivan");
				expected.add("Jack");
				expected.add("Keith");
				expected.add("Larry");
				expected.add("Michael");
				expected.add("Nigel");
				expected.add("Oswald");
				expected.add("Patrick");
				expected.add("Quentin");
				expected.add("Richard");
				expected.add("Stephen");
				expected.add("Thomas");
				expected.add("Ulysses");
				expected.add("Victor");
				expected.add("William");
				expected.add("Xavier");
				expected.add("Yorick");
				expected.add("Zachary");
				expected.add("Alfred");
				expected.add("Bert");
				expected.add("Charles");
				expected.add("David");
				expected.add("Edward");
				expected.add("Fred");
				expected.add("George");
				expected.add("Harry");
				expected.add("Ivan");
				expected.add("Jack");
				expected.add("Keith");
				expected.add("Larry");
				expected.add("Michael");
				expected.add("Nigel");
				expected.add("Oswald");
				expected.add("Patrick");
				expected.add("Quentin");
				expected.add("Richard");
				expected.add("Stephen");
				expected.add("Thomas");
				expected.add("Ulysses");
				expected.add("Victor");
				expected.add("William");
				expected.add("Xavier");
				expected.add("Yorick");
				expected.add("Zachary");
				expected.add("Alfred");
				expected.add("Bert");
				expected.add("Charles");
				expected.add("David");
				expected.add("Edward");
				expected.add("Fred");
				expected.add("George");
				expected.add("Harry");
				expected.add("Ivan");
				expected.add("Jack");
				expected.add("Keith");
				expected.add("Larry");
				expected.add("Michael");
				expected.add("Nigel");
				expected.add("Oswald");
				expected.add("Patrick");
				expected.add("Quentin");
				expected.add("Richard");
				expected.add("Stephen");
				expected.add("Thomas");
				expected.add("Ulysses");
				expected.add("Victor");
				expected.add("William");
				expected.add("Xavier");
				expected.add("Yorick");
				expected.add("Zachary");
				expected.add("Alfred");
	