// DownloadFolderTag_1Test.java
package org.heal.tag.download;

import org.heal.module.download.DownloadQueueBean;
import org.heal.module.metadata.ShortMetadataBean;
import org.heal.util.FileLocator;
import javax.servlet.jsp.tagext.TagSupport;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link DownloadFolderTag}.
* It contains ten unit test cases for the {@link DownloadFolderTag#doEndTag()} method.
*/
class DownloadFolderTag_1Test {

    /**
    * Test method for {@link DownloadFolderTag#doEndTag()}.
    */
    @Test
    void testDoEndTag() {
        DownloadFolderTag tag = new DownloadFolderTag();
        tag.setFileLocator(new FileLocator());
        tag.setDownloadQueue(new DownloadQueueBean());
        tag.setMetadata(new ShortMetadataBean());
        tag.setFolderId("1");
        tag.setFolderName("folder1");
        tag.setFolderPath("folder1");
        tag.setFolderUrl("folder1");
        tag.setFolderSize(100);
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.setFolderSizeStr("100");
        tag.