// FactorizeTest.java
package original;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Factorize}.
* It contains ten unit test cases for the {@link Factorize#factorize(int)} method.
*/
class FactorizeTest {

    @Test
    void testFactorize() {
        List<Integer> expected = new ArrayList<Integer>();
        List<Integer> actual = new ArrayList<Integer>();
        expected.add(2);
        actual = Factorize.factorize(4);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(8);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(16);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(32);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(64);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(128);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(256);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(512);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(1024);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(2048);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(4096);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(8192);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(16384);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(32768);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(65536);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(131072);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(262144);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(524288);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(1048576);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(2097152);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(4194304);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(8388608);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(16777216);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(33554432);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(67108864);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(134217728);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(268435456);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(536870912);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(1073741824);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(2147483648);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(4294967296);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(8589934592);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(17179869184);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(34359738368);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(68719476736);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(137438953472);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(274877906944);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(549755813888);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(1099511627776);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(2199023255552);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(4398046511104);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(8796093022208);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(17592186044416);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(35184372088832);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(70368744177664);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(140737488355328);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(281474976710656);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(562949953421312);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(1125899906842624);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(2251799813685248);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(4503599627370496);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(9007199254740992);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(18014398509481984);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(36028797018963968);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(72057594037927936);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(144115188075855872);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(288230376151711744);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize.factorize(576460752303423488);
        assertEquals(expected, actual);
        expected.add(2);
        actual = Factorize