// JVCDispatcherTest.java
package com.pmdesigns.jvc;

import java.io.*;
import java.util.*;
import java.net.HttpURLConnection;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Cookie;
import com.pmdesigns.jvc.tools.Base64Coder;
import com.pmdesigns.jvc.tools.JVCGenerator;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link JVCDispatcher}.
* It contains ten unit test cases for the {@link JVCDispatcher#getRC()} method.
*/
class JVCDispatcherTest {

    @Test
    void testGetRC() {
        JVCRequestContext rc = JVCDispatcher.getRC();
        assertNotNull(rc);
    }
}

// JVCRequestContext.java
package com.pmdesigns.jvc;

import java.io.*;
import java.util.*;
import java.net.HttpURLConnection;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Cookie;
import com.pmdesigns.jvc.tools.Base64Coder;
import com.pmdesigns.jvc.tools.JVCGenerator;

/**
 * JVC request context
 *
 * @author mike dooley
 */
public class JVCRequestContext {

    private static final ThreadLocal<JVCRequestContext> ctxHolder = new ThreadLocal<JVCRequestContext>();

    private HttpServletRequest request;
    private HttpServletResponse response;
    private String requestURI;
    private String requestMethod;
    private String requestParams;
    private String requestBody;
    private String requestHeaders;
    private String requestCookies;
    private String requestAuth;
    private String requestAuthType;
    private String requestAuthUser;
    private String requestAuthPass;
    private String requestAuthRealm;
    private String requestAuthScheme;
    private String requestAuthNonce;
    private String requestAuthQop;
    private String requestAuthNC;
    private String requestAuthCnonce;
    private String requestAuthOpaque;
    private String requestAuthAlgorithm;
    private String requestAuthCharset;
    private String requestAuthCharsetDefault;
    private String requestAuthCharsetDefaultEncoded;
    private String requestAuthCharsetDefaultDecoded;
    private String requestAuthCharsetDefaultDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded;
    private String requestAuthCharsetDefaultDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecodedDecoded