// CategoryMembersFull_1Test.java
package net.sourceforge.jwbf.mediawiki.actions.queries;

import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_11;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_12;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_13;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_14;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_15;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_16;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.bots.util.JwbfException;
import net.sourceforge.jwbf.mediawiki.actions.util.SupportedBy;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import net.sourceforge.jwbf.mediawiki.contentRep.CategoryItem;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link CategoryMembersFull}.
* It contains ten unit test cases for the {@link CategoryMembersFull#hasNext()} method.
*/
class CategoryMembersFull_1Test {

    /**
    * Test method for {@link CategoryMembersFull#hasNext()}.
    */
    @Test
    void testHasNext() {
        CategoryMembersFull testee = new CategoryMembersFull(new MediaWikiBot(), "test");
        testee.setContinueStr("test");
        testee.setLimit(10);
        testee.setCmTitle("test");
        testee.setCmType("test");
        testee.setCmDir("test");
        testee.setCmLimit("test");
        testee.setCmNamespace("test");
        testee.setCmProp("test");
        testee.setCmContinue("test");
        testee.setCmRedirects("test");
        testee.setCmContent("test");
        testee.setCmConverttitles("test");
        testee.setCmInprop("test");
        testee.setCmSort("test");
        testee.setCmDir("test");
        testee.setCmFrom("test");
        testee.setCmTo("test");
        testee.setCmWhat("test");
        testee.setCmExport("test");
        testee.setCmTranscluded("test");
        testee.setCmShowRedirects("test");
        testee.setCmShowHidden("test");
        testee.setCmShowSubpages("test");
        testee.setCmShowPages("test");
        testee.setCmShowPatrolled("test");
        testee.setCmShowUnpatrolled("test");
        testee.setCmShowDisambig("test");
        testee.setCmShowFragments("test");
        testee.setCmShowBroken("test");
        testee.setCmShowAll("test");
        testee.setCmShowCategories("test");
        testee.setCmShowImages("test");
        testee.setCmShowFiles("test");
        testee.setCmShowLanguages("test");
        testee.setCmShowUsers("test");
        testee.setCmShowWanted("test");
        testee.setCmShowRedirects("test");
        testee.setCmShowShortdesc("test");
        testee.setCmShowTimestamps("test");
        testee.setCmShowFlags("test");
        testee.setCmShowPatrolled("test");
        testee.setCmShowNewPages("test");
        testee.setCmShowLog("test");
        testee.setCmShowAncientPages("test");
        testee.setCmShowLonelyPages("test");
        testee.setCmShowProtectedPages("test");
        testee.setCmShowUncategorizedPages("test");
        testee.setCmShowPagesIncluding("test");
        testee.setCmShowRevisions("test");
        testee.setCmShowDeleted("test");
        testee.setCmShowOnlyArticles("test");
        testee.setCmShowUserContribs("test");
        testee.setCmShowMinor("test");
        testee.setCmShowCategorizedPages("test");
        testee.setCmShowWantedCategories("test");
        testee.setCmShowUnusedCategories("test");
        testee.setCmShowRandom("test");
        testee.setCmShowAncientCategories("test");
        testee.setCmShowLonelyCategories("test");
        testee.setCmShowSubcategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowHiddenCategories("test");
        testee.setCmShowEmptyCategories("test");
        testee.setCmShowCategoriesIncluding("test");
        testee.setCmShowPagesRedirectsOnly("test");
        testee.setCmShowSubpagesIncluding("test");
        testee.setCmShowTemplatesIncluding("test");
        testee.setCmShowTransclusionsIncluding("test");
        testee.setCmShowRevisionsIncluding("test");
        testee.setCmShowFilesIncluding("test");
        testee.setCmShowImagesIncluding("test");
        testee.setCmShowCategoriesRedirectsOnly("test");
        testee.setCmShowInterlanguageLinks("test");
        testee.setCmShowExtLinks("test");
        testee.setCmShowBadges("test");
        testee.setCmShowTables("test");
        testee.setCmShowProperties("test");
        testee.setCmShowPictures("test");
        testee.setCmShowPortal("test");
        testee.setCmShowTemplatePages("test");
        testee.setCmShowTemplateRedirects("test");
        testee.setCmShowCategoriesWithSubpages("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedTemplates("test");
        testee.setCmShowUncategorizedFiles("test");
        testee.setCmShowUncategorizedImages("test");
        testee.setCmShowUncategorizedPages("test");
        testee.setCmShowUncategorizedTemplates("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.setCmShowUncategorizedCategories("test");
        testee.