// CategoryMembersFull_2Test.java
package net.sourceforge.jwbf.mediawiki.actions.queries;

import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_11;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_12;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_13;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_14;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_15;
import static net.sourceforge.jwbf.mediawiki.actions.MediaWiki.Version.MW1_16;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import lombok.extern.slf4j.Slf4j;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.bots.util.JwbfException;
import net.sourceforge.jwbf.mediawiki.actions.util.SupportedBy;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import net.sourceforge.jwbf.mediawiki.contentRep.CategoryItem;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link CategoryMembersFull}.
* It contains ten unit test cases for the {@link CategoryMembersFull#next()} method.
*/
class CategoryMembersFull_2Test {

    /**
    * Test method for {@link CategoryMembersFull#next()}.
    */
    @Test
    void testNext() {
        CategoryMembersFull testee = new CategoryMembersFull(new MediaWikiBot(), "Category:Test");
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();
        testee.prepareNextRequest();