// JniInchiStructure_5Test.java
package net.sf.jniinchi;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link JniInchiStructure}.
* It contains ten unit test cases for the {@link JniInchiStructure#getStereo0D(int)} method.
*/
class JniInchiStructure_5Test {

    private static final String INCHI_STRING = "InChI=1S/C6H12O6/c1-2-4-6-5-3-1/h1-6H";
    private static final String INCHI_KEY = "<KEY>";
    private static final String INCHI_AUX_INFO = "AuxInfo=1/2/1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6";
    private static final String INCHI_BASIS_INFO = "BASIS-INFO=1/2/1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6";
    private static final String INCHI_BASIS_ATOM_COUNTS = "BASIS-ATOM-COUNTS=(6,6,6,6,6,6)";
    private static final String INCHI_BASIS_ATOM_MAP = "BASIS-ATOM-MAP=(1,5,2,6,3,7,4,8,5,9,6,10,7,11,8,12)";
    private static final String INCHI_BASIS_ATOM_TYPES = "BASIS-ATOM-TYPES=(C,C,C,C,C,C)";
    private static final String INCHI_BASIS_ATOM_CHARGES = "BASIS-ATOM-CHARGES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_RADICALS = "BASIS-ATOM-RADICALS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_VALENCES = "BASIS-ATOM-VALENCES=(4,4,4,4,4,4)";
    private static final String INCHI_BASIS_ATOM_STEREO_CONFIGS = "BASIS-ATOM-STEREO-CONFIGS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_PARITIES = "BASIS-ATOM-PARITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_AFFINITIES = "BASIS-ATOM-ELECTRON-AFFINITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_NEGATIVES = "BASIS-ATOM-ELECTRON-NEGATIVES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_STRUCS = "BASIS-ATOM-ELECTRON-STRUCS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_SUBSTITUENTS = "BASIS-ATOM-ELECTRON-SUBSTITUENTS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIRS = "BASIS-ATOM-ELECTRON-PAIRS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_MAP = "BASIS-ATOM-ELECTRON-PAIR-MAP=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ORDERS = "BASIS-ATOM-ELECTRON-PAIR-ORDERS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ORIG_ATOMS = "BASIS-ATOM-ELECTRON-PAIR-ORIG-ATOMS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ORIG_ATOMS_ORDERS = "BASIS-ATOM-ELECTRON-PAIR-ORIG-ATOMS-ORDERS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_PARITIES = "BASIS-ATOM-ELECTRON-PAIR-PARITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_AFFINITIES = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-AFFINITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_NEGATIVES = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-NEGATIVES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_STRUCS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-STRUCS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_SUBSTITUENTS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-SUBSTITUENTS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIRS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIRS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_MAP = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-MAP=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ORDERS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ORDERS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ORIG_ATOMS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ORIG-ATOMS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ORIG_ATOMS_ORDERS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ORIG-ATOMS-ORDERS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_PARITIES = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-PARITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ELECTRON_AFFINITIES = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ELECTRON-AFFINITIES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ELECTRON_NEGATIVES = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ELECTRON-NEGATIVES=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ELECTRON_STRUCS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ELECTRON-STRUCS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ELECTRON_SUBSTITUENTS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ELECTRON-SUBSTITUENTS=(0,0,0,0,0,0)";
    private static final String INCHI_BASIS_ATOM_ELECTRON_PAIR_ELECTRON_PAIR_ELECTRON_PAIRS = "BASIS-ATOM-ELECTRON-PAIR-ELECTRON-PAIR-ELECTRON-PAIRS=(0,0,