// ModernChatServer_5Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#sendSecureTextMessage(TextMessage)} method.
*/
class ModernChatServer_5Test {

    /**
     * Test of sendSecureTextMessage method, of class ModernChatServer.
     * @throws java.rmi.RemoteException
     */
    @Test
    void testSendSecureTextMessage() throws RemoteException {
        System.out.println("sendSecureTextMessage");
        TextMessage msg = new TextMessage();
        msg.setFromUserId(1);
        msg.setToUserId(2);
        msg.setMsg("Hello");
        msg.setMsgId(1);
        msg.setMsgTime(Calendar.getInstance().getTime());
        msg.setMsgStatus(IConstant.MSG_STATUS_SENT);
        msg.setMsgTargetType(IConstant.USER_CHAT);
        msg.setMsgType(IConstant.MSG_TYPE_TEXT);
        msg.setMsgUserId(1);
        msg.setMsgUserName("Ooransa");
        msg.setMsgUserSurname("Ooransa");
        msg.setMsgUserEmail("<EMAIL>");
        msg.setMsgUserPassword("<PASSWORD>");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria");
        msg.setMsgUserCity("Algiers");
        msg.setMsgUserAddress("Algiers");
        msg.setMsgUserPhone("00213456789");
        msg.setMsgUserMobile("00213456789");
        msg.setMsgUserImage("image");
        msg.setMsgUserStatus(IConstant.USER_STATUS_ONLINE);
        msg.setMsgUserType(IConstant.USER_TYPE_NORMAL);
        msg.setMsgUserGender(IConstant.USER_GENDER_MALE);
        msg.setMsgUserBirthDate(Calendar.getInstance().getTime());
        msg.setMsgUserCountry("Algeria