// ModernChatServer_6Test.java
package osa.ora.server;

import java.net.URISyntaxException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;
import osa.ora.server.bd.UsersBD;
import osa.ora.server.beans.BinaryMessage;
import osa.ora.server.beans.Group;
import osa.ora.server.beans.IConstant;
import osa.ora.server.beans.LoginBean;
import osa.ora.server.beans.ResultBean;
import osa.ora.server.beans.Room;
import osa.ora.server.beans.ServerSettingBean;
import osa.ora.server.beans.TextMessage;
import osa.ora.server.beans.User;
import osa.ora.server.client.ClientInterface;
import osa.ora.server.threads.SendKickOffByLoginMessageThread;
import osa.ora.server.threads.SendKickOffMessageThread;
import osa.ora.server.threads.SendRefreshContactThread;
import osa.ora.server.threads.SendUserUpdatedStatusThread;
import osa.ora.server.utils.StringEncoder64;
import osa.ora.server.utils.StringEncrypter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link ModernChatServer}.
* It contains ten unit test cases for the {@link ModernChatServer#sendBinaryMessage(BinaryMessage)} method.
*/
class ModernChatServer_6Test {

    /**
     * Test of sendBinaryMessage method, of class ModernChatServer.
     * @throws java.rmi.RemoteException
     */
    @Test
    void testSendBinaryMessage() throws RemoteException {
        System.out.println("sendBinaryMessage");
        BinaryMessage msg = new BinaryMessage();
        msg.setAction(IConstant.REQUEST);
        msg.setFromUserId(1);
        msg.setToUserId(2);
        msg.setFileName("test.txt");
        msg.setFileSize(100);
        msg.setFileData(new byte[100]);
        msg.setFileId(1);
        msg.setFileExtension("txt");
        msg.setFileMimeType("text/plain");
        msg.setFileDescription("test file");
        msg.setFileDate(Calendar.getInstance().getTime());
        msg.setFileSender(1);
        msg.setFileReceiver(2);
        msg.setFileStatus(IConstant.ONLINE);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg.setFileId(1);
        msg