// GameTest.java
package net.virtualinfinity.atrobots.game;

import net.virtualinfinity.atrobots.arena.FrameBuilder;
import net.virtualinfinity.atrobots.arena.RoundState;
import net.virtualinfinity.atrobots.arena.SimulationObserver;
import net.virtualinfinity.atrobots.compiler.RobotFactory;
import net.virtualinfinity.atrobots.robot.FinalRobotScore;
import net.virtualinfinity.atrobots.robot.Robot;
import net.virtualinfinity.atrobots.robot.RobotScore;
import net.virtualinfinity.atrobots.robot.RobotScoreKeeper;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Game}.
* It contains ten unit test cases for the {@link Game#stepRound()} method.
*/
class GameTest {

    @Test
    void testStepRound() {
        final Game game = new Game();
        final RobotFactory robotFactory = new RobotFactory();
        final Robot robot = robotFactory.createRobot("TestRobot");
        final RobotScoreKeeper scoreKeeper = new RobotScoreKeeper();
        final SimulationObserver simulationObserver = new SimulationObserver();
        final FrameBuilder frameBuilder = new FrameBuilder();
        final RoundState roundState = new RoundState(robot, scoreKeeper, simulationObserver, frameBuilder);
        game.setRound(new Round(roundState));
        game.stepRound();
        assertEquals(1, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(2, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(3, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(4, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(5, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(6, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(7, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(8, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(9, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(10, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(11, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(12, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(13, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(14, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(15, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(16, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(17, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(18, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(19, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(20, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(21, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(22, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(23, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(24, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(25, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(26, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(27, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(28, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(29, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(30, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(31, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(32, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(33, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(34, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(35, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(36, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(37, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(38, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(39, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(40, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(41, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(42, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(43, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(44, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(45, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(46, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(47, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(48, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(49, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(50, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(51, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(52, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(53, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(54, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(55, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(56, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(57, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(58, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(59, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(60, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(61, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(62, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(63, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(64, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(65, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(66, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(67, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(68, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(69, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(70, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(71, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(72, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(73, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(74, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(75, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(76, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(77, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(78, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(79, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(80, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(81, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(82, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(83, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(84, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(85, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(86, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(87, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(88, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(89, scoreKeeper.getScore().getScore());
        game.stepRound();
        assertEquals(90, scoreKeeper.getScore().getScore());
        game.stepRound();
       