// Drink_1Test.java
package bierse.model;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;
import bierse.view.MyKeyMap;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Drink}.
* It contains ten unit test cases for the {@link Drink#save()} method.
*/
class Drink_1Test {

    /**
     * Test of the {@link Drink#save()} method.
     */
    @Test
    void testSave() {
        Drink drink = new Drink();
        drink.setName("TestDrink");
        drink.setMinPrice(10);
        drink.setMaxPrice(20);
        drink.setStartPrice(15);
        drink.setTargetAmount(100);
        drink.setDeltaAmount(10);
        drink.setMaxStep(10);
        drink.setUsed(true);
        drink.setKey(KeyEvent.VK_A);
        File file = drink.save();
        assertNotNull(file);
        assertTrue(file.exists());
        assertTrue(file.isFile());
        assertTrue(file.getName().endsWith(".xml"));
        assertTrue(file.getName().startsWith("TestDrink"));
        assertTrue(file.getName().length() > 10);
        assertTrue(file.getName().length() < 20);
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains(".xml"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName().contains("TestDrink"));
        assertTrue(file.getName