// BomberClient_1Test.java
package client;

import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Observable;
import java.util.Vector;
import javax.swing.ImageIcon;
import messages.Message;
import messages.global.InfoRequestMsg;
import messages.global.JoinSessionMsg;
import messages.global.MapInfo;
import messages.global.SessionDetailsMsg;
import messages.round.ClientQuitRunningSessionMsg;
import org.apache.log4j.Logger;
import client.gui.StartFrame;
import client.network.ClientMsgReceiver;
import client.network.ClientMsgSender;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link BomberClient}.
* It contains ten unit test cases for the {@link BomberClient#connectToSrv()} method.
*/
class BomberClient_1Test {

    private static final Logger logger = Logger.getLogger(BomberClient_1Test.class);
    private static final String serverName = "localhost";
    private static final int serverPort = 1234;
    private static final String sessionName = "testSession";
    private static final String playerName = "testPlayer";
    private static final String playerName2 = "testPlayer2";
    private static final String playerName3 = "testPlayer3";
    private static final String playerName4 = "testPlayer4";
    private static final String playerName5 = "testPlayer5";
    private static final String playerName6 = "testPlayer6";
    private static final String playerName7 = "testPlayer7";
    private static final String playerName8 = "testPlayer8";
    private static final String playerName9 = "testPlayer9";
    private static final String playerName10 = "testPlayer10";
    private static final String playerName11 = "testPlayer11";
    private static final String playerName12 = "testPlayer12";
    private static final String playerName13 = "testPlayer13";
    private static final String playerName14 = "testPlayer14";
    private static final String playerName15 = "testPlayer15";
    private static final String playerName16 = "testPlayer16";
    private static final String playerName17 = "testPlayer17";
    private static final String playerName18 = "testPlayer18";
    private static final String playerName19 = "testPlayer19";
    private static final String playerName20 = "testPlayer20";
    private static final String playerName21 = "testPlayer21";
    private static final String playerName22 = "testPlayer22";
    private static final String playerName23 = "testPlayer23";
    private static final String playerName24 = "testPlayer24";
    private static final String playerName25 = "testPlayer25";
    private static final String playerName26 = "testPlayer26";
    private static final String playerName27 = "testPlayer27";
    private static final String playerName28 = "testPlayer28";
    private static final String playerName29 = "testPlayer29";
    private static final String playerName30 = "testPlayer30";
    private static final String playerName31 = "testPlayer31";
    private static final String playerName32 = "testPlayer32";
    private static final String playerName33 = "testPlayer33";
    private static final String playerName34 = "testPlayer34";
    private static final String playerName35 = "testPlayer35";
    private static final String playerName36 = "testPlayer36";
    private static final String playerName37 = "testPlayer37";
    private static final String playerName38 = "testPlayer38";
    private static final String playerName39 = "testPlayer39";
    private static final String playerName40 = "testPlayer40";
    private static final String playerName41 = "testPlayer41";
    private static final String playerName42 = "testPlayer42";
    private static final String playerName43 = "testPlayer43";
    private static final String playerName44 = "testPlayer44";
    private static final String playerName45 = "testPlayer45";
    private static final String playerName46 = "testPlayer46";
    private static final String playerName47 = "testPlayer47";
    private static final String playerName48 = "testPlayer48";
    private static final String playerName49 = "testPlayer49";
    private static final String playerName50 = "testPlayer50";
    private static final String playerName51 = "testPlayer51";
    private static final String playerName52 = "testPlayer52";
    private static final String playerName53 = "testPlayer53";
    private static final String playerName54 = "testPlayer54";
    private static final String playerName55 = "testPlayer55";
    private static final String playerName56 = "testPlayer56";
    private static final String playerName57 = "testPlayer57";
    private static final String playerName58 = "testPlayer58";
    private static final String playerName59 = "testPlayer59";
    private static final String playerName60 = "testPlayer60";
    private static final String playerName61 = "testPlayer61";
    private static final String playerName62 = "testPlayer62";
    private static final String playerName63 = "testPlayer63";
    private static final String playerName64 = "testPlayer64";
    private static final String playerName65 = "testPlayer65";
    private static final String playerName66 = "testPlayer66";
    private static final String playerName67 = "testPlayer67";
    private static final String playerName68 = "testPlayer68";
    private static final String playerName69 = "testPlayer69";
    private static final String playerName70 = "testPlayer70";
    private static final String playerName71 = "testPlayer71";
    private static final String playerName72 = "testPlayer72";
    private static final String playerName73 = "testPlayer73";
    private static final String playerName74 = "testPlayer74";
    private static final String playerName75 = "testPlayer75";
    private static final String playerName76 = "testPlayer76";
    private static final String playerName77 = "testPlayer77";
    private static final String playerName78 = "testPlayer78";
    private static final String playerName79 = "testPlayer79";
    private static final String playerName80 = "testPlayer80";
    private static final String playerName81 = "testPlayer81";
    private static final String playerName82 = "testPlayer82";
    private static final String playerName83 = "testPlayer83";
    private static final String playerName84 = "testPlayer84";
    private static final String playerName85 = "testPlayer85";
    private static final String playerName86 = "testPlayer86";
    private static final String playerName87 = "testPlayer87";
    private static final String playerName88 = "testPlayer88";
    private static final String playerName89 = "testPlayer89";
    private static final String playerName90 = "testPlayer90";
    private static final String playerName91 = "testPlayer91";
    private static final String playerName92 = "testPlayer92";
    private static final String playerName93 = "testPlayer93";
    private static final String playerName94 = "testPlayer94";
    private static final String playerName95 = "testPlayer95";
    private static final String playerName96 = "testPlayer96";
    private static final String playerName97 = "testPlayer97";
    private static final String playerName98 = "testPlayer98";
    private static final String playerName99 = "testPlayer99";
    private static final String playerName100 = "testPlayer100";
    private static final String playerName101 = "testPlayer101";
    private static final String playerName102 = "testPlayer102";
    private static final String playerName103 = "testPlayer103";
    private static final String playerName104 = "testPlayer104";
    private static final String playerName105 = "testPlayer105";
    private static final String playerName106 = "testPlayer106";
    private static final String playerName107 = "testPlayer107";
    private static final String playerName108 = "testPlayer108";
    private static final String playerName109 = "testPlayer109";
    private static final String playerName110 = "testPlayer110";
    private static final String playerName111 = "testPlayer111";
    private static final String playerName112 = "testPlayer112";
    private static final String playerName113 = "testPlayer113";
    private static final String playerName114 = "testPlayer114";
    private static final String playerName115 = "testPlayer115";
    private static final String playerName116 = "testPlayer116";
    private static final String playerName117 = "testPlayer117";
    private static final String playerName118 = "testPlayer118";
    private static final String playerName119 = "testPlayer119";
    private static final String playerName120 = "testPlayer120";