// XmlFunctions_1Test.java
package common;

import java.io.File;
import java.io.IOException;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import org.apache.log4j.Logger;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link XmlFunctions}.
* It contains ten unit test cases for the {@link XmlFunctions#findXmlNodes(String)} method.
*/
class XmlFunctions_1Test {

    private static final Logger logger = Logger.getLogger(XmlFunctions_1Test.class);
    private static final String xmlFile = "src/test/resources/test.xml";
    private static final String xmlFile2 = "src/test/resources/test2.xml";
    private static final String xmlFile3 = "src/test/resources/test3.xml";
    private static final String xmlFile4 = "src/test/resources/test4.xml";
    private static final String xmlFile5 = "src/test/resources/test5.xml";
    private static final String xmlFile6 = "src/test/resources/test6.xml";
    private static final String xmlFile7 = "src/test/resources/test7.xml";
    private static final String xmlFile8 = "src/test/resources/test8.xml";
    private static final String xmlFile9 = "src/test/resources/test9.xml";
    private static final String xmlFile10 = "src/test/resources/test10.xml";
    private static final String xmlFile11 = "src/test/resources/test11.xml";
    private static final String xmlFile12 = "src/test/resources/test12.xml";
    private static final String xmlFile13 = "src/test/resources/test13.xml";
    private static final String xmlFile14 = "src/test/resources/test14.xml";
    private static final String xmlFile15 = "src/test/resources/test15.xml";
    private static final String xmlFile16 = "src/test/resources/test16.xml";
    private static final String xmlFile17 = "src/test/resources/test17.xml";
    private static final String xmlFile18 = "src/test/resources/test18.xml";
    private static final String xmlFile19 = "src/test/resources/test19.xml";
    private static final String xmlFile20 = "src/test/resources/test20.xml";
    private static final String xmlFile21 = "src/test/resources/test21.xml";
    private static final String xmlFile22 = "src/test/resources/test22.xml";
    private static final String xmlFile23 = "src/test/resources/test23.xml";
    private static final String xmlFile24 = "src/test/resources/test24.xml";
    private static final String xmlFile25 = "src/test/resources/test25.xml";
    private static final String xmlFile26 = "src/test/resources/test26.xml";
    private static final String xmlFile27 = "src/test/resources/test27.xml";
    private static final String xmlFile28 = "src/test/resources/test28.xml";
    private static final String xmlFile29 = "src/test/resources/test29.xml";
    private static final String xmlFile30 = "src/test/resources/test30.xml";
    private static final String xmlFile31 = "src/test/resources/test31.xml";
    private static final String xmlFile32 = "src/test/resources/test32.xml";
    private static final String xmlFile33 = "src/test/resources/test33.xml";
    private static final String xmlFile34 = "src/test/resources/test34.xml";
    private static final String xmlFile35 = "src/test/resources/test35.xml";
    private static final String xmlFile36 = "src/test/resources/test36.xml";
    private static final String xmlFile37 = "src/test/resources/test37.xml";
    private static final String xmlFile38 = "src/test/resources/test38.xml";
    private static final String xmlFile39 = "src/test/resources/test39.xml";
    private static final String xmlFile40 = "src/test/resources/test40.xml";
    private static final String xmlFile41 = "src/test/resources/test41.xml";
    private static final String xmlFile42 = "src/test/resources/test42.xml";
    private static final String xmlFile43 = "src/test/resources/test43.xml";
    private static final String xmlFile44 = "src/test/resources/test44.xml";
    private static final String xmlFile45 = "src/test/resources/test45.xml";
    private static final String xmlFile46 = "src/test/resources/test46.xml";
    private static final String xmlFile47 = "src/test/resources/test47.xml";
    private static final String xmlFile48 = "src/test/resources/test48.xml";
    private static final String xmlFile49 = "src/test/resources/test49.xml";
    private static final String xmlFile50 = "src/test/resources/test50.xml";
    private static final String xmlFile51 = "src/test/resources/test51.xml";
    private static final String xmlFile52 = "src/test/resources/test52.xml";
    private static final String xmlFile53 = "src/test/resources/test53.xml";
    private static final String xmlFile54 = "src/test/resources/test54.xml";
    private static final String xmlFile55 = "src/test/resources/test55.xml";
    private static final String xmlFile56 = "src/test/resources/test56.xml";
    private static final String xmlFile57 = "src/test/resources/test57.xml";
    private static final String xmlFile58 = "src/test/resources/test58.xml";
    private static final String xmlFile59 = "src/test/resources/test59.xml";
    private static final String xmlFile60 = "src/test/resources/test60.xml";
    private static final String xmlFile61 = "src/test/resources/test61.xml";
    private static final String xmlFile62 = "src/test/resources/test62.xml";
    private static final String xmlFile63 = "src/test/resources/test63.xml";
    private static final String xmlFile64 = "src/test/resources/test64.xml";
    private static final String xmlFile65 = "src/test/resources/test65.xml";
    private static final String xmlFile66 = "src/test/resources/test66.xml";
    private static final String xmlFile67 = "src/test/resources/test67.xml";
    private static final String xmlFile68 = "src/test/resources/test68.xml";
    private static final String xmlFile69 = "src/test/resources/test69.xml";
    private static final String xmlFile70 = "src/test/resources/test70.xml";
    private static final String xmlFile71 = "src/test/resources/test71.xml";
    private static final String xmlFile72 = "src/test/resources/test72.xml";
    private static final String xmlFile73 = "src/test/resources/test73.xml";
    private static final String xmlFile74 = "src/test/resources/test74.xml";
    private static final String xmlFile75 = "src/test/resources/test75.xml";
    private static final String xmlFile76 = "src/test/resources/test76.xml";
    private static final String xmlFile77 = "src/test/resources/test77.xml";
    private static final String xmlFile78 = "src/test/resources/test78.xml";
    private static final String xmlFile79 = "src/test/resources/test79.xml";
    private static final String xmlFile80 = "src/test/resources/test80.xml";
    private static final String xmlFile81 = "src/test/resources/test81.xml";
    private static final String xmlFile82 = "src/test/resources/test82.xml";
    private static final String xmlFile83 = "src/test/resources/test83.xml";
    private static final String xmlFile84 = "src/test/resources/test84.xml";
    private static final String xmlFile85 = "src/test/resources/test85.xml";
    private static final String xmlFile86 = "src/test/resources/test86.xml";
    private static final String xmlFile87 = "src/test/resources/test87.xml";