// Login_4Test.java
package com.browsersoft.aacs;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.TimeZone;
import javax.security.auth.login.LoginException;
import org.apache.log4j.FileAppender;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.SimpleLayout;
import com.browsersoft.aacs.xacml.PDPadapter;
import com.browsersoft.aacs.xacml.RequestBuilder;
import com.sun.xacml.Indenter;
import com.sun.xacml.ctx.RequestCtx;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link Login}.
* It contains ten unit test cases for the {@link Login#authenticate()} method.
*/
class Login_4Test {

    private static final Logger cat = Logger.getLogger(Login_4Test.class);
    private static final String USER_ID = "admin";
    private static final String PASSWORD = "<PASSWORD>";
    private static final String AUTH_TYPE = "local";
    private static final String IP_ADDR = "127.0.0.1";
    private static final String USER_NAME = "admin";
    private static final String USER_EMAIL = "<EMAIL>";
    private static final String USER_PHONE = "1234567890";
    private static final String USER_COUNTRY = "US";
    private static final String USER_STATE = "CA";
    private static final String USER_CITY = "San Francisco";
    private static final String USER_ZIP = "94105";
    private static final String USER_ADDRESS = "1234567890";
    private static final String USER_ROLE = "admin";
    private static final String USER_GROUP = "admin";
    private static final String USER_GROUP_2 = "admin2";
    private static final String USER_GROUP_3 = "admin3";
    private static final String USER_GROUP_4 = "admin4";
    private static final String USER_GROUP_5 = "admin5";
    private static final String USER_GROUP_6 = "admin6";
    private static final String USER_GROUP_7 = "admin7";
    private static final String USER_GROUP_8 = "admin8";
    private static final String USER_GROUP_9 = "admin9";
    private static final String USER_GROUP_10 = "admin10";
    private static final String USER_GROUP_11 = "admin11";
    private static final String USER_GROUP_12 = "admin12";
    private static final String USER_GROUP_13 = "admin13";
    private static final String USER_GROUP_14 = "admin14";
    private static final String USER_GROUP_15 = "admin15";
    private static final String USER_GROUP_16 = "admin16";
    private static final String USER_GROUP_17 = "admin17";
    private static final String USER_GROUP_18 = "admin18";
    private static final String USER_GROUP_19 = "admin19";
    private static final String USER_GROUP_20 = "admin20";
    private static final String USER_GROUP_21 = "admin21";
    private static final String USER_GROUP_22 = "admin22";
    private static final String USER_GROUP_23 = "admin23";
    private static final String USER_GROUP_24 = "admin24";
    private static final String USER_GROUP_25 = "admin25";
    private static final String USER_GROUP_26 = "admin26";
    private static final String USER_GROUP_27 = "admin27";
    private static final String USER_GROUP_28 = "admin28";
    private static final String USER_GROUP_29 = "admin29";
    private static final String USER_GROUP_30 = "admin30";
    private static final String USER_GROUP_31 = "admin31";
    private static final String USER_GROUP_32 = "admin32";
    private static final String USER_GROUP_33 = "admin33";
    private static final String USER_GROUP_34 = "admin34";
    private static final String USER_GROUP_35 = "admin35";
    private static final String USER_GROUP_36 = "admin36";
    private static final String USER_GROUP_37 = "admin37";
    private static final String USER_GROUP_38 = "admin38";
    private static final String USER_GROUP_39 = "admin39";
    private static final String USER_GROUP_40 = "admin40";
    private static final String USER_GROUP_41 = "admin41";
    private static final String USER_GROUP_42 = "admin42";
    private static final String USER_GROUP_43 = "admin43";
    private static final String USER_GROUP_44 = "admin44";
    private static final String USER_GROUP_45 = "admin45";
    private static final String USER_GROUP_46 = "admin46";
    private static final String USER_GROUP_47 = "admin47";
    private static final String USER_GROUP_48 = "admin48";
    private static final String USER_GROUP_49 = "admin49";
    private static final String USER_GROUP_50 = "admin50";
    private static final String USER_GROUP_51 = "admin51";
    private static final String USER_GROUP_52 = "admin52";
    private static final String USER_GROUP_53 = "admin53";
    private static final String USER_GROUP_54 = "admin54";
    private static final String USER_GROUP_55 = "admin55";
    private static final String USER_GROUP_56 = "admin56";
    private static final String USER_GROUP_57 = "admin57";
    private static final String USER_GROUP_58 = "admin58";
    private static final String USER_GROUP_59 = "admin59";
    private static final String USER_GROUP_60 = "admin60";
    private static final String USER_GROUP_61 = "admin61";
    private static final String USER_GROUP_62 = "admin62";
    private static final String USER_GROUP_63 = "admin63";
    private static final String USER_GROUP_64 = "admin64";
    private static final String USER_GROUP_65 = "admin65";
    private static final String USER_GROUP_66 = "admin66";
    private static final String USER_GROUP_67 = "admin67";
    private static final String USER_GROUP_68 = "admin68";
    private static final String USER_GROUP_69 = "admin69";
    private static final String USER_GROUP_70 = "admin70";
    private static final String USER_GROUP_71 = "admin71";
    private static final String USER_GROUP_72 = "admin72";
    private static final String USER_GROUP_73 = "admin73";
    private static final String USER_GROUP_74 = "admin74";
    private static final String USER_GROUP_75 = "admin75";
    private static final String USER_GROUP_76 = "admin76";
    private static final String USER_GROUP_77 = "admin77";
    private static final String USER_GROUP_78 = "admin78";
    private static final String USER_GROUP_79 = "admin79";
    private static final String USER_GROUP_80 = "admin80";
    private static final String USER_GROUP_81 = "admin81";
    private static final String USER_GROUP_82 = "admin82";
    private static final String USER_GROUP_83 = "admin83";
    private static final String USER_GROUP_84 = "admin84";
    private static final String USER_GROUP_85 = "admin85";
    private static final String USER_GROUP_86 = "admin86";
    private static final String USER_GROUP_87 = "admin87";
    private static final String USER_GROUP_88 = "admin88";
    private static final String USER_GROUP_89 = "admin89";
    private static final String USER_GROUP_90 = "admin90";
    private static final String USER_GROUP_91 = "admin91";
    private static final String USER_GROUP_92 = "admin92";
    private static final String USER_GROUP_93 = "admin93";
    private static final String USER_GROUP_94 = "admin94";
    private static final String USER_GROUP_95 = "admin95";
    private static final String USER_GROUP_96 = "admin96";
    private static final String USER_GROUP_97 = "admin97";
    private static final String USER_GROUP_98 = "admin98";
    private static final String USER_GROUP_99 = "admin99";
    private static final String USER_GROUP_100 = "admin100";
    private static final String USER_GROUP_101 = "admin101";
    private static final String USER_GROUP_102 = "admin102";
    private static final String USER_GROUP_103 = "admin103";
    private static final String USER_GROUP_104 = "admin104";
    private static final String USER_GROUP_105 = "admin105";
    private static final String USER_GROUP_106 = "admin106";
   