// HtmlContentParserTest1.java
package org.asphodel.parser;

import au.id.jericho.lib.html.Source;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.net.URL;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link HtmlContentParser}.
* It contains ten unit test cases for the {@link HtmlContentParser#extractText(Reader)} method.
*/
class HtmlContentParserTest1 {
private static Log log = LogFactory.getLog(HtmlContentParserTest1.class);
		private static final String TEST_FILE_NAME = "test.html";
		private static final String TEST_FILE_NAME_2 = "test2.html";
		private static final String TEST_FILE_NAME_3 = "test3.html";
		private static final String TEST_FILE_NAME_4 = "test4.html";
		private static final String TEST_FILE_NAME_5 = "test5.html";
		private static final String TEST_FILE_NAME_6 = "test6.html";
		private static final String TEST_FILE_NAME_7 = "test7.html";
		private static final String TEST_FILE_NAME_8 = "test8.html";
		private static final String TEST_FILE_NAME_9 = "test9.html";
		private static final String TEST_FILE_NAME_10 = "test10.html";
		private static final String TEST_FILE_NAME_11 = "test11.html";
		private static final String TEST_FILE_NAME_12 = "test12.html";
		private static final String TEST_FILE_NAME_13 = "test13.html";
		private static final String TEST_FILE_NAME_14 = "test14.html";
		private static final String TEST_FILE_NAME_15 = "test15.html";
		private static final String TEST_FILE_NAME_16 = "test16.html";
		private static final String TEST_FILE_NAME_17 = "test17.html";
		private static final String TEST_FILE_NAME_18 = "test18.html";
		private static final String TEST_FILE_NAME_19 = "test19.html";
		private static final String TEST_FILE_NAME_20 = "test20.html";
		private static final String TEST_FILE_NAME_21 = "test21.html";
		private static final String TEST_FILE_NAME_22 = "test22.html";
		private static final String TEST_FILE_NAME_23 = "test23.html";
		private static final String TEST_FILE_NAME_24 = "test24.html";
		private static final String TEST_FILE_NAME_25 = "test25.html";
		private static final String TEST_FILE_NAME_26 = "test26.html";
		private static final String TEST_FILE_NAME_27 = "test27.html";
		private static final String TEST_FILE_NAME_28 = "test28.html";
		private static final String TEST_FILE_NAME_29 = "test29.html";
		private static final String TEST_FILE_NAME_30 = "test30.html";
		private static final String TEST_FILE_NAME_31 = "test31.html";
		private static final String TEST_FILE_NAME_32 = "test32.html";
		private static final String TEST_FILE_NAME_33 = "test33.html";
		private static final String TEST_FILE_NAME_34 = "test34.html";
		private static final String TEST_FILE_NAME_35 = "test35.html";
		private static final String TEST_FILE_NAME_36 = "test36.html";
		private static final String TEST_FILE_NAME_37 = "test37.html";
		private static final String TEST_FILE_NAME_38 = "test38.html";
		private static final String TEST_FILE_NAME_39 = "test39.html";
		private static final String TEST_FILE_NAME_40 = "test40.html";
		private static final String TEST_FILE_NAME_41 = "test41.html";
		private static final String TEST_FILE_NAME_42 = "test42.html";
		private static final String TEST_FILE_NAME_43 = "test43.html";
		private static final String TEST_FILE_NAME_44 = "test44.html";
		private static final String TEST_FILE_NAME_45 = "test45.html";
		private static final String TEST_FILE_NAME_46 = "test46.html";
		private static final String TEST_FILE_NAME_47 = "test47.html";
		private static final String TEST_FILE_NAME_48 = "test48.html";
		private static final String TEST_FILE_NAME_49 = "test49.html";
		private static final String TEST_FILE_NAME_50 = "test50.html";
		private static final String TEST_FILE_NAME_51 = "test51.html";
		private static final String TEST_FILE_NAME_52 = "test52.html";
		private static final String TEST_FILE_NAME_53 = "test53.html";
		private static final String TEST_FILE_NAME_54 = "test54.html";
		private static final String TEST_FILE_NAME_55 = "test55.html";
		private static final String TEST_FILE_NAME_56 = "test56.html";
		private static final String TEST_FILE_NAME_57 = "test57.html";
		private static final String TEST_FILE_NAME_58 = "test58.html";
		private static final String TEST_FILE_NAME_59 = "test59.html";
		private static final String TEST_FILE_NAME_60 = "test60.html";
		private static final String TEST_FILE_NAME_61 = "test61.html";
		private static final String TEST_FILE_NAME_62 = "test62.html";
		private static final String TEST_FILE_NAME_63 = "test63.html";
		private static final String TEST_FILE_NAME_64 = "test64.html";
		private static final String TEST_FILE_NAME_65 = "test65.html";
		private static final String TEST_FILE_NAME_66 = "test66.html";
		private static final String TEST_FILE_NAME_67 = "test67.html";
		private static final String TEST_FILE_NAME_68 = "test68.html";
		private static final String TEST_FILE_NAME_69 = "test69.html";
		private static final String TEST_FILE_NAME_70 = "test70.html";
		private static final String TEST_FILE_NAME_71 = "test71.html";
		private static final String TEST_FILE_NAME_72 = "test72.html";
		private static final String TEST_FILE_NAME_73 = "test73.html";
		private static final String TEST_FILE_NAME_74 = "test74.html";
		private static final String TEST_FILE_NAME_75 = "test75.html";
		private static final String TEST_FILE_NAME_76 = "test76.html";
		private static final String TEST_FILE_NAME_77 = "test77.html";
		private static final String TEST_FILE_NAME_78 = "test78.html";
		private static final String TEST_FILE_NAME_79 = "test79.html";
		private static final String TEST_FILE_NAME_80 = "test80.html";
		private static final String TEST_FILE_NAME_81 = "test81.html";
		private static final String TEST_FILE_NAME_82 = "test82.html";
		private static final String TEST_FILE_NAME_83 = "test83.html";
		private static final String TEST_FILE_NAME_84 = "test84.html";
		private static final String TEST_FILE_NAME_85 = "test85.html";
		private static final String TEST_FILE_NAME_86 = "test86.html";
		private static final String TEST_FILE_NAME_87 = "test87.html";
		private static final String TEST_FILE_NAME_88 = "test88.html";
		private static final String TEST_FILE_NAME_89 = "test89.html";
		private static final String TEST_FILE_NAME_90 = "test90.html";
		private static final String TEST_FILE_NAME_91 = "test91.html";
		private static final String TEST_FILE_NAME_92 = "test92.html";
		private static final String TEST_FILE_NAME_93 = "test93.html";
		private static final String TEST_FILE_NAME_94 = "test94.html";
		private static final String TEST_FILE_NAME_95 = "test95.html";
		private static final String TEST_FILE_NAME_96 = "test96.html";
		private static final String TEST_FILE_NAME_97 =