// LineReader_1Test.java
package fr.pingtimeout.jtail.io;

import fr.pingtimeout.jtail.io.index.FileIndex;
import fr.pingtimeout.jtail.util.JTailLogger;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link LineReader}.
* It contains ten unit test cases for the {@link LineReader#readBlock(int, int)} method.
*/
class LineReader_1Test {

    private static final String FILE_NAME = "src/test/resources/fr/pingtimeout/jtail/io/LineReader_1Test.txt";
    private static final int NB_LINES = 10;
    private static final int NB_LINES_TO_READ = 5;
    private static final int NB_LINES_TO_READ_2 = 3;
    private static final int NB_LINES_TO_READ_3 = 10;
    private static final int NB_LINES_TO_READ_4 = 11;
    private static final int NB_LINES_TO_READ_5 = 12;
    private static final int NB_LINES_TO_READ_6 = 13;
    private static final int NB_LINES_TO_READ_7 = 14;
    private static final int NB_LINES_TO_READ_8 = 15;
    private static final int NB_LINES_TO_READ_9 = 16;
    private static final int NB_LINES_TO_READ_10 = 17;
    private static final int NB_LINES_TO_READ_11 = 18;
    private static final int NB_LINES_TO_READ_12 = 19;
    private static final int NB_LINES_TO_READ_13 = 20;
    private static final int NB_LINES_TO_READ_14 = 21;
    private static final int NB_LINES_TO_READ_15 = 22;
    private static final int NB_LINES_TO_READ_16 = 23;
    private static final int NB_LINES_TO_READ_17 = 24;
    private static final int NB_LINES_TO_READ_18 = 25;
    private static final int NB_LINES_TO_READ_19 = 26;
    private static final int NB_LINES_TO_READ_20 = 27;
    private static final int NB_LINES_TO_READ_21 = 28;
    private static final int NB_LINES_TO_READ_22 = 29;
    private static final int NB_LINES_TO_READ_23 = 30;
    private static final int NB_LINES_TO_READ_24 = 31;
    private static final int NB_LINES_TO_READ_25 = 32;
    private static final int NB_LINES_TO_READ_26 = 33;
    private static final int NB_LINES_TO_READ_27 = 34;
    private static final int NB_LINES_TO_READ_28 = 35;
    private static final int NB_LINES_TO_READ_29 = 36;
    private static final int NB_LINES_TO_READ_30 = 37;
    private static final int NB_LINES_TO_READ_31 = 38;
    private static final int NB_LINES_TO_READ_32 = 39;
    private static final int NB_LINES_TO_READ_33 = 40;
    private static final int NB_LINES_TO_READ_34 = 41;
    private static final int NB_LINES_TO_READ_35 = 42;
    private static final int NB_LINES_TO_READ_36 = 43;
    private static final int NB_LINES_TO_READ_37 = 44;
    private static final int NB_LINES_TO_READ_38 = 45;
    private static final int NB_LINES_TO_READ_39 = 46;
    private static final int NB_LINES_TO_READ_40 = 47;
    private static final int NB_LINES_TO_READ_41 = 48;
    private static final int NB_LINES_TO_READ_42 = 49;
    private static final int NB_LINES_TO_READ_43 = 50;
    private static final int NB_LINES_TO_READ_44 = 51;
    private static final int NB_LINES_TO_READ_45 = 52;
    private static final int NB_LINES_TO_READ_46 = 53;
    private static final int NB_LINES_TO_READ_47 = 54;
    private static final int NB_LINES_TO_READ_48 = 55;
    private static final int NB_LINES_TO_READ_49 = 56;
    private static final int NB_LINES_TO_READ_50 = 57;
    private static final int NB_LINES_TO_READ_51 = 58;
    private static final int NB_LINES_TO_READ_52 = 59;
    private static final int NB_LINES_TO_READ_53 = 60;
    private static final int NB_LINES_TO_READ_54 = 61;
    private static final int NB_LINES_TO_READ_55 = 62;
    private static final int NB_LINES_TO_READ_56 = 63;
    private static final int NB_LINES_TO_READ_57 = 64;
    private static final int NB_LINES_TO_READ_58 = 65;
    private static final int NB_LINES_TO_READ_59 = 66;
    private static final int NB_LINES_TO_READ_60 = 67;
    private static final int NB_LINES_TO_READ_61 = 68;
    private static final int NB_LINES_TO_READ_62 = 69;
    private static final int NB_LINES_TO_READ_63 = 70;
    private static final int NB_LINES_TO_READ_64 = 71;
    private static final int NB_LINES_TO_READ_65 = 72;
    private static final int NB_LINES_TO_READ_66 = 73;
    private static final int NB_LINES_TO_READ_67 = 74;
    private static final int NB_LINES_TO_READ_68 = 75;
    private static final int NB_LINES_TO_READ_69 = 76;
    private static final int NB_LINES_TO_READ_70 = 77;
    private static final int NB_LINES_TO_READ_71 = 78;
    private static final int NB_LINES_TO_READ_72 = 79;
    private static final int NB_LINES_TO_READ_73 = 80;
    private static final int NB_LINES_TO_READ_74 = 81;
    private static final int NB_LINES_TO_READ_75 = 82;
    private static final int NB_LINES_TO_READ_76 = 83;
    private static final int NB_LINES_TO_READ_77 = 84;
    private static final int NB_LINES_TO_READ_78 = 85;
    private static final int NB_LINES_TO_READ_79 = 86;
    private static final int NB_LINES_TO_READ_80 = 87;
    private static final int NB_LINES_TO_READ_81 = 88;
    private static final int NB_LINES_TO_READ_82 = 89;
    private static final int NB_LINES_TO_READ_83 = 90;
    private static final int NB_LINES_TO_READ_84 = 91;
    private static final int NB_LINES_TO_READ_85 = 92;
    private static final int NB_LINES_TO_READ_86 = 93;
    private static final int NB_LINES_TO_READ_87 = 94;
    private static final int NB_LINES_TO_READ_88 = 95;
    private static final int NB_LINES_TO_READ_89 = 96;
    private static final int NB_LINES_TO_READ_90 = 97;
    private static final int NB_LINES_TO_READ_91 = 98;
    private static final int NB_LINES_TO_READ_92 = 99;
    private static final int NB_LINES_TO_READ_93 = 100;
    private static final int NB_LINES_TO_READ_94 = 101;
    private static final int NB_LINES_TO_READ_95 = 102;
    private static final int NB_LINES_TO_READ_96 = 103;
    private static final int NB_LINES_TO_READ_97 = 104;
    private static final int NB_LINES_TO_READ_98 = 105;