// LineReader_0Test.java
package fr.pingtimeout.jtail.io;

import fr.pingtimeout.jtail.io.index.FileIndex;
import fr.pingtimeout.jtail.util.JTailLogger;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link LineReader}.
* It contains ten unit test cases for the {@link LineReader#readLine(int)} method.
*/
class LineReader_0Test {

    private static final String FILE_NAME = "src/test/resources/fr/pingtimeout/jtail/io/LineReader_0Test.txt";
    private static final int LINE_COUNT = 10;
    private static final int LINE_LENGTH = 10;
    private static final int LINE_LENGTH_WITH_EOL = LINE_LENGTH + 1;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR = LINE_LENGTH + 2;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF = LINE_LENGTH + 3;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF = LINE_LENGTH + 4;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF = LINE_LENGTH + 5;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR = LINE_LENGTH + 6;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 7;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 8;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 9;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 10;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 11;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 12;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 13;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 14;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 15;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 16;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 17;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 18;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 19;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 20;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 21;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 22;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 23;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 24;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF = LINE_LENGTH + 25;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR = LINE_LENGTH + 26;
    private static final int LINE_LENGTH_WITH_EOL_AND_CR_AND_LF_AND_CRLF_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_CR_AND_LF_AND_