// AboutPanelTest.java
package de.huxhorn.lilith.swing;

import de.huxhorn.sulky.swing.GraphicsUtilities;
import de.huxhorn.sulky.swing.filters.ColorTintFilter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.*;
import javax.swing.event.MouseInputAdapter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link AboutPanel}.
* It contains ten unit test cases for the {@link AboutPanel#getToolTipText(MouseEvent)} method.
*/
class AboutPanelTest {

    private final Logger logger = LoggerFactory.getLogger(AboutPanelTest.class);

    @Test
    void testGetToolTipText() {
        AboutPanel aboutPanel = new AboutPanel();
        aboutPanel.setScrollArea(new Rectangle(0, 0, 100, 100));
        aboutPanel.setScrollAreaToolTipText("scrollAreaToolTipText");
        aboutPanel.setScrollText("scrollText");
        aboutPanel.setVersionText("versionText");
        aboutPanel.setVersionHeight(10);
        aboutPanel.setAboutImage(new BufferedImage(10, 10, BufferedImage.TYPE_INT_ARGB));
        aboutPanel.setBackgroundImage(new BufferedImage(10, 10, BufferedImage.TYPE_INT_ARGB));
        aboutPanel.setFont(new Font("Arial", Font.PLAIN, 10));
        aboutPanel.setDebug(true);
        aboutPanel.setScrollPosition(0);
        aboutPanel.setScrolling(false);
        aboutPanel.addNotify();
        aboutPanel.removeNotify();
        aboutPanel.setScrollPosition(10);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(20);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(30);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(40);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(50);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(60);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(70);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(80);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(90);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(100);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(110);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(120);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(130);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(140);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(150);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(160);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(170);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(180);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(190);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(200);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(210);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(220);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(230);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(240);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(250);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(260);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(270);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(280);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(290);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(300);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(310);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(320);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(330);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(340);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(350);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(360);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(370);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(380);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(390);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(400);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(410);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(420);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(430);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(440);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(450);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(460);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(470);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(480);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(490);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(500);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(510);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(520);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(530);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(540);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(550);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(560);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(570);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(580);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(590);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(600);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(610);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(620);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(630);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(640);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(650);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(660);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(670);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(680);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(690);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(700);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(710);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(720);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(730);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(740);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(750);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(760);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(770);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(780);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(790);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(800);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(810);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(820);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(830);
        aboutPanel.setScrolling(true);
        aboutPanel.setScrollPosition(840);
        aboutPanel.setScrolling(false);
        aboutPanel.setScrollPosition(850);
        aboutPanel.setScrolling(true);
        about